const CATALOG = {
  "products": [
    {
      "id": "1",
      "filter": "streaming",
      "name": "Net Caarasco",
      "brand": "Netflix",
      "sub": "1 mes - Perfil",
      "description": "",
      "type": "Perfil individual",
      "duration": "1 mes",
      "pen": 16,
      "original_pen": 18,
      "banner_url": "banners/netflix_premium_banner.png",
      "features": [
        "Resolución 4K en contenido seleccionado",
        "Acceso a un amplio catálogo de películas y series",
        "Compatible con Smart TV, celular, PC y tablet",
        "Sin publicidad"
      ],
      "note": "La activación del servicio se realiza de forma digital y el acceso es inmediato después de la compra.",
      "sort_order": 10,
      "cat_sort_order": 10,
      "palette": "netflix",
      "stock_quantity": null,
      "active": true,
      "out_of_stock": false,
      "is_oferta": false
    },
    {
      "id": "3",
      "filter": "streaming",
      "name": "Disney+ Estandar",
      "brand": "Disney",
      "sub": "1 mes - Perfil",
      "description": "",
      "type": "Plan Estándar",
      "duration": "1 mes - 30 días",
      "pen": 9,
      "original_pen": 12,
      "banner_url": "assets/c332492799027e7c.png",
      "features": [
        "Calidad Full HD",
        "Catálogo completo",
        "Sin anuncios",
        "Descargas permitidas"
      ],
      "note": "Plan estándar sin ESPN. Acceso completo al catalogo Disney+, Marvel, Star Wars y Pixar.",
      "sort_order": 20,
      "cat_sort_order": 30,
      "palette": "disney",
      "stock_quantity": null,
      "active": true,
      "out_of_stock": false,
      "is_oferta": false
    },
    {
      "id": "45",
      "filter": "software",
      "name": "Chat GPT PLUS",
      "brand": "Chat GPT",
      "sub": "Cuenta compartida",
      "description": "",
      "type": "Cuenta compartida",
      "duration": "1 mes",
      "pen": 20,
      "original_pen": 25,
      "banner_url": "assets/3daa59def87061f5.png",
      "features": [
        "Acceso a la versión premium de Chat GPT con capacidades avanzadas de generación de texto",
        "Análisis de texto y respuesta más precisa y detallada",
        "Capacidad de procesar y responder a preguntas y solicitudes de manera más eficiente",
        "Asistencia personalizada para tareas y proyectos"
      ],
      "note": "El uso de Chat GPT PLUS requiere una conexión a Internet estable y un dispositivo compatible para aprovechar al máximo sus funcionalidades.",
      "sort_order": 30,
      "cat_sort_order": 70,
      "palette": "",
      "stock_quantity": null,
      "active": true,
      "out_of_stock": false,
      "is_oferta": true
    },
    {
      "id": "7",
      "filter": "streaming",
      "name": "Paramount+",
      "brand": "Paramount",
      "sub": "1 mes - Perfil",
      "description": "",
      "type": "Perfil",
      "duration": "1 mes",
      "pen": 18,
      "original_pen": 25,
      "banner_url": "assets/8e71c005b81ec659.png",
      "features": [
        "Acceso a una amplia variedad de películas y series de Paramount+",
        "Disfruta de estrenos exclusivos y contenido original",
        "Accede a canales en vivo y deportes en directo"
      ],
      "note": "El acceso a Paramount+ requiere una conexión a internet estable y puede variar según la región y el plan elegido. El acceso incluye la posibilidad de crear perfiles individuales y disfrutar de contenido en alta definición, siempre y cuando esté disponible en el plan seleccionado.",
      "sort_order": 40,
      "cat_sort_order": 40,
      "palette": "",
      "stock_quantity": null,
      "active": true,
      "out_of_stock": false,
      "is_oferta": true
    },
    {
      "id": "40",
      "filter": "diseño",
      "name": "Canva Pro x 1 AÑO",
      "brand": "Canva",
      "sub": "1 año - Cuenta",
      "description": "",
      "type": "A tu correo propio",
      "duration": "1 año",
      "pen": 15,
      "original_pen": 20,
      "banner_url": "assets/d86c7dcd4ad4f162.png",
      "features": [
        "Plantillas premium",
        "Exportacion ilimitada",
        "Precio especial"
      ],
      "note": "Ahorra con el plan anual de Canva Pro. 12 meses de acceso completo.",
      "sort_order": 50,
      "cat_sort_order": 30,
      "palette": "canva_año",
      "stock_quantity": null,
      "active": true,
      "out_of_stock": false,
      "is_oferta": true
    },
    {
      "id": "9",
      "filter": "streaming",
      "name": "Apple TV+",
      "brand": "Apple TV+",
      "sub": "1 mes - Perfil",
      "description": "",
      "type": "Perfil individual",
      "duration": "1 mes",
      "pen": 8,
      "original_pen": 10,
      "banner_url": "banners/appletv_banner.png",
      "features": [
        "4K HDR Dolby Vision",
        "Contenido Apple Original",
        "Sin publicidad"
      ],
      "note": "Acceso completo a todo el catalogo Apple TV+. Series y peliculas originales exclusivas.",
      "sort_order": 70,
      "cat_sort_order": 120,
      "palette": "",
      "stock_quantity": null,
      "active": true,
      "out_of_stock": false,
      "is_oferta": false
    },
    {
      "id": "2",
      "filter": "streaming",
      "name": "Prime Video",
      "brand": "Amazon",
      "sub": "1 mes - Perfil",
      "description": "",
      "type": "Perfil individual",
      "duration": "1 mes",
      "pen": 10,
      "original_pen": null,
      "banner_url": "banners/prime_banner.png",
      "features": [
        "Acceso a un amplio catálogo de películas y series",
        "Disfruta de resolución Full HD y 4K en seleccionados títulos",
        "Incluye canales en vivo y deportes en directo",
        "Perfiles personalizados para hasta 6 usuarios",
        "Descarga de contenido para ver sin conexión a internet"
      ],
      "note": "La activación de la cuenta se realiza de forma digital y el acceso es inmediato después de la compra",
      "sort_order": 80,
      "cat_sort_order": 20,
      "palette": "prime",
      "stock_quantity": null,
      "active": true,
      "out_of_stock": false,
      "is_oferta": false
    },
    {
      "id": "71",
      "filter": "streaming",
      "name": "Prime Video X 3 MESES",
      "brand": "Prime Video",
      "sub": "3 meses - Perfil",
      "description": "",
      "type": "Perfil individual",
      "duration": "3 meses",
      "pen": 17,
      "original_pen": 28.5,
      "banner_url": "assets/f00dc0fd16007587.png",
      "features": [
        "Acceso a una amplia variedad de películas y series según disponibilidad del plan",
        "Disfruta de contenido en alta calidad de video, incluyendo Full HD",
        "Crea perfiles individuales para una experiencia personalizada",
        "Disfruta de estrenos exclusivos y contenido original de la plataforma"
      ],
      "note": "El servicio de streaming requiere una conexión a internet estable para funcionar correctamente y es necesario aceptar los términos y condiciones de uso.",
      "sort_order": 90,
      "cat_sort_order": 20,
      "palette": "",
      "stock_quantity": null,
      "active": true,
      "out_of_stock": false,
      "is_oferta": true
    },
    {
      "id": "33",
      "filter": "diseño",
      "name": "CapCut Pro 1 mes",
      "brand": "CapCut",
      "sub": "1 mes - Cuenta",
      "description": "",
      "type": "Cuenta Pro",
      "duration": "1 mes",
      "pen": 40,
      "original_pen": null,
      "banner_url": "banners/capcut_banner.png",
      "features": [
        "Sin marca de agua",
        "Efectos premium",
        "Exportacion 4K"
      ],
      "note": "Acceso completo a CapCut Pro. Edita videos sin marca de agua y con efectos premium.",
      "sort_order": 100,
      "cat_sort_order": 0,
      "palette": "capcut",
      "stock_quantity": null,
      "active": true,
      "out_of_stock": true,
      "is_oferta": false
    },
    {
      "id": "12",
      "filter": "streaming",
      "name": "OleadaTV x 1 mes",
      "brand": "OleadaTV",
      "sub": "1 mes - 1 dispositivo",
      "description": "",
      "type": "Perfil compartido",
      "duration": "1 mes",
      "pen": 15,
      "original_pen": 18,
      "banner_url": "banners/oleadatv_1_dispositivo_x_1_mes_banner.png",
      "features": [
        "Acceso a un amplio catálogo de películas y series",
        "Transmisiones en vivo de deportes y canales en vivo",
        "Resolución Full HD para una experiencia de visualización óptima",
        "Perfiles personales para una experiencia de usuario personalizada",
        "Disponibilidad de subtítulos y doblaje en varios idiomas"
      ],
      "note": "La activación del servicio se realiza de forma digital y el uso del perfil compartido está sujeto a las condiciones del plan seleccionado.",
      "sort_order": 110,
      "cat_sort_order": 110,
      "palette": "oleadatv",
      "stock_quantity": null,
      "active": true,
      "out_of_stock": false,
      "is_oferta": false
    },
    {
      "id": "42",
      "filter": "diseño",
      "name": "Duolingo SUPER, 1 mes",
      "brand": "Duolingo",
      "sub": "1 mes a tu correo propio",
      "description": "",
      "type": "Correo propio",
      "duration": "1 mes",
      "pen": 15,
      "original_pen": 22,
      "banner_url": "assets/7d17e77bb1475ca4.png",
      "features": [
        "Lecciones divertidas y efectivas",
        "Más de 40 idiomas para hablar",
        "Practica cuando quieras",
        "Manten tu racha y supera tus metas"
      ],
      "note": "Únete a millones de personas que ya están aprendiendo en Duolingo",
      "sort_order": 120,
      "cat_sort_order": 0,
      "palette": "",
      "stock_quantity": null,
      "active": true,
      "out_of_stock": false,
      "is_oferta": false
    },
    {
      "id": "72",
      "filter": "streaming",
      "name": "Prime Video x 6 MESES",
      "brand": "Prime Video",
      "sub": "6 meses Perfil",
      "description": "",
      "type": "Perfil individual",
      "duration": "6 meses",
      "pen": 31,
      "original_pen": 57,
      "banner_url": "assets/e2b5e0dc6915dadf.png",
      "features": [
        "Acceso a una amplia variedad de películas y series de estreno",
        "Disfruta de contenido en alta definición, según disponibilidad del plan",
        "Disfruta de una experiencia de visualización en varios dispositivos",
        "Accede a documentales y contenido exclusivo de Prime Video"
      ],
      "note": "El servicio de streaming requiere una conexión a internet estable para funcionar correctamente",
      "sort_order": 130,
      "cat_sort_order": 50,
      "palette": "",
      "stock_quantity": null,
      "active": true,
      "out_of_stock": false,
      "is_oferta": true
    },
    {
      "id": "43",
      "filter": "diseño",
      "name": "Duolingo SUPER, 1 AÑO CORREO PROPIO",
      "brand": "Duolingo",
      "sub": "A TU CORREO",
      "description": "",
      "type": "Cuenta completa",
      "duration": "1 año",
      "pen": 120,
      "original_pen": 180,
      "banner_url": "assets/35a6c3a470a65ec6.png",
      "features": [
        "Acceso a cursos premium de idiomas",
        "Recursos educativos interactivos",
        "Plantillas y herramientas para el aprendizaje",
        "Almacenamiento de progreso y seguimiento de avance"
      ],
      "note": "La cuenta se activa automáticamente después de la compra y es válida para un año desde la fecha de activación.",
      "sort_order": 140,
      "cat_sort_order": 0,
      "palette": "",
      "stock_quantity": null,
      "active": true,
      "out_of_stock": false,
      "is_oferta": false
    },
    {
      "id": "10",
      "filter": "streaming",
      "name": "IPTV Premium",
      "brand": "IPTV",
      "sub": "1 mes - 1 dispositivo",
      "description": "",
      "type": "1 dispositivo",
      "duration": "1 mes",
      "pen": 12,
      "original_pen": 14,
      "banner_url": "banners/iptv_premium_1_dispositivo__1_mes_banner.png",
      "features": [
        "+10000 canales",
        "Canales en vivo HD/4K",
        "Peliculas y series"
      ],
      "note": "Acceso a mas de 10,000 canales nacionales e internacionales en HD y 4K.",
      "sort_order": 150,
      "cat_sort_order": 150,
      "palette": "iptv",
      "stock_quantity": null,
      "active": true,
      "out_of_stock": false,
      "is_oferta": false
    },
    {
      "id": "67",
      "filter": "streaming",
      "name": "Movistar Play + LA LIGA 1 MAX",
      "brand": "Movistar",
      "sub": "1 mes - Perfil",
      "description": "",
      "type": "Perfil individual",
      "duration": "1 mes",
      "pen": 33,
      "original_pen": 35,
      "banner_url": "assets/5eb655e9ccf4f699.png",
      "features": [
        "Acceso a LA LIGA 1 MAX",
        "Perfiles individuales para una experiencia personalizada",
        "Disfruta de tus partidos favoritos en diferentes dispositivos",
        "Acceso a otros contenidos de entretenimiento en Movistar Play"
      ],
      "note": "El servicio de streaming requiere una conexión a internet estable para funcionar correctamente.",
      "sort_order": 160,
      "cat_sort_order": 140,
      "palette": "",
      "stock_quantity": null,
      "active": true,
      "out_of_stock": false,
      "is_oferta": false
    },
    {
      "id": "4",
      "filter": "streaming",
      "name": "Disney+ Premium + ESPN",
      "brand": "Disney",
      "sub": "1 mes - Perfil individual",
      "description": "",
      "type": "Premium + ESPN",
      "duration": "1 mes",
      "pen": 12,
      "original_pen": 15,
      "banner_url": "assets/bc9f77dba26f1e77.png",
      "features": [
        "Incluye ESPN+",
        "Calidad Ultra HD 4K",
        "Audio Dolby Atmos",
        "Descargas ilimitadas",
        "Sin anuncios",
        "Todo el deporte en vivo"
      ],
      "note": "El plan más completo: Incluye todo el catálogo de Disney, Pixar, Marvel y Star, además de todos los canales de ESPN y eventos deportivos exclusivos en vivo. Disfruta de la mejor resolución 4K y audio envolvente en hasta 4 pantallas simultáneas.",
      "sort_order": 170,
      "cat_sort_order": 40,
      "palette": "disney",
      "stock_quantity": null,
      "active": true,
      "out_of_stock": false,
      "is_oferta": false
    },
    {
      "id": "5",
      "filter": "streaming",
      "name": "HBO Max Estándar",
      "brand": "HBO Max",
      "sub": "1 mes - Perfil",
      "description": "",
      "type": "Plan Estándar",
      "duration": "1 mes",
      "pen": 8,
      "original_pen": 10,
      "banner_url": "assets/c760264228297408.png",
      "features": [
        "Full HD",
        "Series HBO exclusivas",
        "Contenido Warner Bros"
      ],
      "note": "Plan estandar. House of the Dragon, Succession, The Last of Us y todo el catalogo HBO.",
      "sort_order": 180,
      "cat_sort_order": 50,
      "palette": "hbo",
      "stock_quantity": null,
      "active": true,
      "out_of_stock": false,
      "is_oferta": false
    },
    {
      "id": "39",
      "filter": "diseño",
      "name": "Canva Pro 1 mes",
      "brand": "Canva",
      "sub": "1 mes - Cuenta",
      "description": "",
      "type": "Cuenta",
      "duration": "1 mes",
      "pen": 5,
      "original_pen": null,
      "banner_url": "banners/canva_pro_1_mes_banner.png",
      "features": [
        "Plantillas premium",
        "Fondo removedor",
        "Brand Kit completo"
      ],
      "note": "Acceso completo a Canva Pro con todas las funciones desbloqueadas.",
      "sort_order": 190,
      "cat_sort_order": 0,
      "palette": "canva_mes",
      "stock_quantity": null,
      "active": true,
      "out_of_stock": false,
      "is_oferta": false
    },
    {
      "id": "6",
      "filter": "streaming",
      "name": "HBO Max Platino",
      "brand": "HBO Max",
      "sub": "1 mes - Perfil",
      "description": "",
      "type": "Plan Platino",
      "duration": "1 mes",
      "pen": 10,
      "original_pen": 12,
      "banner_url": "assets/ca67863c15c089d9.png",
      "features": [
        "4K Ultra HD",
        "Series HBO exclusivas",
        "Max Originals",
        "Descargas offline"
      ],
      "note": "Plan platino con 4K y descargas. La experiencia HBO mas completa.",
      "sort_order": 200,
      "cat_sort_order": 60,
      "palette": "",
      "stock_quantity": null,
      "active": true,
      "out_of_stock": false,
      "is_oferta": false
    },
    {
      "id": "14",
      "filter": "streaming",
      "name": "DirecTV + Liga Max",
      "brand": "DirecTV",
      "sub": "1 mes - Cuenta",
      "description": "",
      "type": "Un dispositivo",
      "duration": "1 mes",
      "pen": 32,
      "original_pen": 35,
      "banner_url": "assets/1bc81be7ade90424.png",
      "features": [
        "Acceso a la Liga Max en vivo",
        "Transmisiones de alta calidad de los partidos de fútbol",
        "Disponibilidad de partidos en diferentes horarios",
        "Acceso a contenido adicional relacionado con la Liga Max"
      ],
      "note": "CUENTA EXCLUSIVA, SOLO HABRA DOS PERSONAS EN LA CUENTA.\nPerfil DGO EXCLISVO PARA TV – 1 usuario ✔ Acceso a un perfil individual. ✔ Activacion a Televisión. ✔ Activacion por Código. ✔ Calidad de imagen en HD. 📺 Entretenimiento y deportes en vivo Más de 90 canales nacionales e internacionales, incluyendo: Deportes (ESPN, FOX Sports, DSports). Series, películas y noticias. ⚽ Con Liga 1 Max, disfruta la transmisión exclusiva de la Liga 1 peruana, en vivo y en HD. ✨ Beneficios principales: Acceso total a canales y contenido bajo demanda. Perfil ideal para uso personal. Activación inmediata y segura",
      "sort_order": 210,
      "cat_sort_order": 10,
      "palette": "directv",
      "stock_quantity": null,
      "active": true,
      "out_of_stock": false,
      "is_oferta": true
    },
    {
      "id": "11",
      "filter": "streaming",
      "name": "Universal+",
      "brand": "Universal+",
      "sub": "1 mes - Perfil",
      "description": "",
      "type": "Perfil",
      "duration": "1 mes",
      "pen": 8.9,
      "original_pen": null,
      "banner_url": "assets/10bb0205cd75a2ec.png",
      "features": [
        "Series Universal",
        "Contenido exclusivo",
        "Estrenos anticipados"
      ],
      "note": "Perfil en cuenta compartida. Acceso completo al catalogo Universal+.",
      "sort_order": 220,
      "cat_sort_order": 90,
      "palette": "universalplus",
      "stock_quantity": null,
      "active": true,
      "out_of_stock": false,
      "is_oferta": false
    },
    {
      "id": "38",
      "filter": "software",
      "name": "Gemini Pro + 5TB x 1 mes",
      "brand": "Google",
      "sub": "Invitación a tu propio correo",
      "description": "",
      "type": "Cuenta Personal",
      "duration": "1 mes",
      "pen": 15,
      "original_pen": null,
      "banner_url": "banners/gemini_pro__5tb_banner.png",
      "features": [
        "Gemini Pro IA",
        "5TB Google Drive",
        "Google One incluido"
      ],
      "note": "Para la activación se le enviará una invitación por correo al grupo familiar para que obtenga los beneficios. El paquete incluye acceso a todas las funciones de Gemini pro y 5TB de almacenamiento en Google One, permitiendo a los usuarios gestionar y almacenar sus archivos y datos de manera segura y eficiente.",
      "sort_order": 230,
      "cat_sort_order": 10,
      "palette": "gemini",
      "stock_quantity": null,
      "active": true,
      "out_of_stock": false,
      "is_oferta": false
    },
    {
      "id": "68",
      "filter": "streaming",
      "name": "Claro Video",
      "brand": "Claro",
      "sub": "1 mes Perfil",
      "description": "",
      "type": "Perfil individual",
      "duration": "1 mes",
      "pen": 20,
      "original_pen": 25,
      "banner_url": "assets/8464602aa4cbfc92.png",
      "features": [
        "Acceso a una amplia variedad de películas y series según disponibilidad del plan",
        "Disfruta de contenido en alta definición, incluyendo Full HD y 4K",
        "Crea perfiles individuales para una experiencia personalizada",
        "Accede a deportes en vivo y canales de televisión según la disponibilidad del plan"
      ],
      "note": "El servicio de streaming requiere una conexión a internet estable para funcionar correctamente",
      "sort_order": 240,
      "cat_sort_order": 130,
      "palette": "",
      "stock_quantity": null,
      "active": true,
      "out_of_stock": true,
      "is_oferta": false
    },
    {
      "id": "13",
      "filter": "streaming",
      "name": "ViX Premium",
      "brand": "ViX",
      "sub": "1 mes - Perfil",
      "description": "",
      "type": "Perfil individual",
      "duration": "1 mes",
      "pen": 10,
      "original_pen": 12,
      "banner_url": "banners/vix_banner.png",
      "features": [
        "Acceso a un amplio catálogo de películas y series",
        "Transmisiones en vivo de deportes y canales de noticias",
        "Resolución 4K disponible para contenido seleccionado",
        "Perfiles personales para hasta 5 usuarios",
        "Disponible en varios dispositivos, incluyendo TV, tabletas y smartphones"
      ],
      "note": "La activación de la cuenta se realiza de forma digital y el servicio está disponible según las condiciones del plan seleccionado.",
      "sort_order": 250,
      "cat_sort_order": 180,
      "palette": "",
      "stock_quantity": null,
      "active": true,
      "out_of_stock": false,
      "is_oferta": false
    },
    {
      "id": "41",
      "filter": "animeydramas",
      "name": "Crunchyroll Mega Fan",
      "brand": "Crunchyroll",
      "sub": "1 mes - Perfil",
      "description": "",
      "type": "Perfil individual",
      "duration": "1 mes",
      "pen": 8,
      "original_pen": null,
      "banner_url": "assets/62fb93f2ee8667da.png",
      "features": [
        "Acceso a un amplio catálogo de anime con subtítulos y doblaje",
        "Disfruta de simulcast de las últimas series de anime",
        "Calidad de video HD para una experiencia de visualización óptima",
        "Acceso multiplataforma para ver anime en diferentes dispositivos"
      ],
      "note": "La cuenta se activará inmediatamente después de la compra y podrá ser utilizada durante el período de suscripción según las condiciones del plan.",
      "sort_order": 260,
      "cat_sort_order": 10,
      "palette": "crunchyroll",
      "stock_quantity": null,
      "active": true,
      "out_of_stock": false,
      "is_oferta": false
    },
    {
      "id": "44",
      "filter": "software",
      "name": "McAfee Antivirus Plus",
      "brand": "McAfee",
      "sub": "Antivirus 1 año",
      "description": "",
      "type": "Licencia digital",
      "duration": "1 año",
      "pen": 78,
      "original_pen": 85,
      "banner_url": "banners/mcafee_antivirus_plus_banner.png",
      "features": [
        "Protección contra virus y malware",
        "Actualizaciones automáticas para mantener la seguridad",
        "Compatibilidad con múltiples dispositivos y sistemas operativos",
        "Herramientas de seguridad incluidas, como firewall y antivirus"
      ],
      "note": "La licencia se activa digitalmente y es válida para uso personal en un dispositivo",
      "sort_order": 270,
      "cat_sort_order": 160,
      "palette": "",
      "stock_quantity": null,
      "active": true,
      "out_of_stock": false,
      "is_oferta": false
    },
    {
      "id": "69",
      "filter": "animeydramas",
      "name": "MUBI",
      "brand": "MUBI",
      "sub": "1 mes Perfil",
      "description": "",
      "type": "Perfil individual",
      "duration": "1 mes",
      "pen": 9,
      "original_pen": 11,
      "banner_url": "assets/b313dfbf21e8950f.png",
      "features": [
        "Acceso a una selección de películas y series de cineastas independientes y emergentes",
        "Perfiles personales para una experiencia de visualización personalizada",
        "Disponibilidad en varios dispositivos, incluyendo smartphones, tablets y televisores",
        "Calidad de video Full HD para una experiencia de visualización óptima"
      ],
      "note": "El servicio de streaming requiere una conexión a Internet estable para funcionar correctamente y ofrece contenido según la disponibilidad del plan seleccionado.",
      "sort_order": 280,
      "cat_sort_order": 20,
      "palette": "",
      "stock_quantity": null,
      "active": true,
      "out_of_stock": false,
      "is_oferta": false
    },
    {
      "id": "46",
      "filter": "software",
      "name": "Autodesk",
      "brand": "Autodesk",
      "sub": "1 año -  A tu correo propio",
      "description": "",
      "type": "Licencia digital",
      "duration": "1 AÑO",
      "pen": 28,
      "original_pen": 35,
      "banner_url": "assets/cec42b48a6e58fe5.png",
      "features": [
        "Acceso a herramientas de diseño y modelado 3D avanzadas",
        "Compatibilidad con múltiples sistemas operativos, incluyendo Windows y macOS",
        "Actualizaciones automáticas para mantener el software actualizado",
        "Uso personal y profesional, ideal para diseñadores y empresas"
      ],
      "note": "La licencia se activa digitalmente después de la compra y requiere una cuenta en el sitio web de Autodesk para acceder a las herramientas y recursos.",
      "sort_order": 290,
      "cat_sort_order": 160,
      "palette": "",
      "stock_quantity": null,
      "active": true,
      "out_of_stock": false,
      "is_oferta": true
    },
    {
      "id": "21",
      "filter": "software",
      "name": "Office 365 Personal a tu Correo Propio",
      "brand": "Microsoft",
      "sub": "1 año - 1 PC o Mac",
      "description": "",
      "type": "Cuenta completa",
      "duration": "1 año",
      "pen": 45,
      "original_pen": 55,
      "banner_url": "banners/office365_banner.png",
      "features": [
        "Acceso a las últimas versiones de Microsoft Office",
        "Almacenamiento en la nube de 1 TB con OneDrive",
        "Compatibilidad con Windows, macOS, iOS y Android",
        "Actualizaciones automáticas para mantener el software actualizado"
      ],
      "note": "La cuenta se activará en tu correo electrónico propio y estará disponible para su uso inmediato después de la compra.",
      "sort_order": 300,
      "cat_sort_order": 170,
      "palette": "office365",
      "stock_quantity": null,
      "active": true,
      "out_of_stock": false,
      "is_oferta": false
    },
    {
      "id": "15",
      "filter": "musica",
      "name": "Spotify Premium x 1 mes",
      "brand": "Spotify",
      "sub": "1 mes - Individual",
      "description": "",
      "type": "Cuenta completa",
      "duration": "1 mes",
      "pen": 15,
      "original_pen": 17,
      "banner_url": "assets/864418ff40746699.png",
      "features": [
        "Reproducción sin anuncios",
        "Descarga offline de música",
        "Alta calidad de audio",
        "Acceso a playlists y podcasts",
        "Uso en varios dispositivos"
      ],
      "note": "La cuenta se activará en un plazo de 1 hora o menos después de la compra y estará disponible para uso inmediato.",
      "sort_order": 310,
      "cat_sort_order": 110,
      "palette": "spotify_mes",
      "stock_quantity": null,
      "active": true,
      "out_of_stock": false,
      "is_oferta": true
    },
    {
      "id": "18",
      "filter": "musica",
      "name": "TIDAL Individual",
      "brand": "TIDAL",
      "sub": "1 mes - Cuenta",
      "description": "",
      "type": "Cuenta individual",
      "duration": "1 mes",
      "pen": 11,
      "original_pen": null,
      "banner_url": "assets/52339961d8db1dc8.png",
      "features": [
        "Calidad HiFi lossless",
        "Dolby Atmos",
        "Sin publicidad"
      ],
      "note": "Audio de maxima calidad. TIDAL HiFi con sonido lossless y Dolby Atmos.",
      "sort_order": 320,
      "cat_sort_order": 0,
      "palette": "tidal_ind",
      "stock_quantity": null,
      "active": true,
      "out_of_stock": false,
      "is_oferta": false
    },
    {
      "id": "19",
      "filter": "musica",
      "name": "TIDAL Familiar",
      "brand": "TIDAL",
      "sub": "1 mes - Hasta 6 personas",
      "description": "",
      "type": "Cuenta familiar",
      "duration": "1 mes",
      "pen": 21,
      "original_pen": null,
      "banner_url": "assets/94385e8fd408b38f.png",
      "features": [
        "Hasta 6 cuentas",
        "HiFi lossless",
        "Perfiles independientes"
      ],
      "note": "Hasta 6 miembros con perfiles separados. Cada uno con su propia biblioteca.",
      "sort_order": 330,
      "cat_sort_order": 0,
      "palette": "",
      "stock_quantity": null,
      "active": true,
      "out_of_stock": false,
      "is_oferta": false
    },
    {
      "id": "22",
      "filter": "software",
      "name": "Office 2024 PERMANENTE",
      "brand": "Microsoft",
      "sub": "Permanente - 1 PC o Mac",
      "description": "",
      "type": "Licencia permanente",
      "duration": "Permanente",
      "pen": 45,
      "original_pen": 60,
      "banner_url": "banners/office_2024_banner.png",
      "features": [
        "Acceso a las últimas herramientas de productividad de Office",
        "Incluye aplicaciones como Word, Excel, PowerPoint y Outlook",
        "Uso personal y profesional sin restricciones",
        "Instalación digital sencilla y rápida"
      ],
      "note": "La licencia es válida para un solo dispositivo y no requiere renovación",
      "sort_order": 340,
      "cat_sort_order": 40,
      "palette": "office2024",
      "stock_quantity": null,
      "active": true,
      "out_of_stock": false,
      "is_oferta": false
    },
    {
      "id": "17",
      "filter": "musica",
      "name": "Spotify Premium x 1 año CORREO PROPIO",
      "brand": "Spotify",
      "sub": "1 año - Individual",
      "description": "",
      "type": "Cuenta completa",
      "duration": "1 año",
      "pen": 119.9,
      "original_pen": 135,
      "banner_url": "banners/spotify_premium_1_ano_a_tu_correo_propio_banner.png",
      "features": [
        "Reproducción de música sin anuncios",
        "Descarga de música para reproducción offline",
        "Alta calidad de audio",
        "Acceso a playlists y podcasts exclusivos",
        "Uso en varios dispositivos"
      ],
      "note": "La cuenta se activará inmediatamente después de la compra y tendrá una duración de un año, según el plan adquirido.",
      "sort_order": 350,
      "cat_sort_order": 0,
      "palette": "spotify_año",
      "stock_quantity": null,
      "active": true,
      "out_of_stock": true,
      "is_oferta": false
    },
    {
      "id": "25",
      "filter": "software",
      "name": "Windows 10 Pro PERMANENTE",
      "brand": "Microsoft",
      "sub": "Permanente - 1 PC",
      "description": "",
      "type": "Licencia OEM",
      "duration": "Permanente",
      "pen": 38,
      "original_pen": 45,
      "banner_url": "assets/65240ae720df530c.png",
      "features": [
        "Acceso a todas las funciones de Windows 10 Pro",
        "Activación digital permanente para 1 PC",
        "Compatibilidad con una amplia variedad de software y hardware",
        "Uso personal y profesional permitido"
      ],
      "note": "La licencia de Windows 10 Pro es para uso en un solo equipo y requiere una instalación válida de Windows para activarla.",
      "sort_order": 360,
      "cat_sort_order": 170,
      "palette": "windows10",
      "stock_quantity": null,
      "active": true,
      "out_of_stock": false,
      "is_oferta": true
    },
    {
      "id": "26",
      "filter": "software",
      "name": "ESET NOD32",
      "brand": "ESET",
      "sub": "1 año - 1 dispositivo",
      "description": "",
      "type": "Licencia digital",
      "duration": "1 año",
      "pen": 43,
      "original_pen": 48,
      "banner_url": "assets/e05044314ef2141d.png",
      "features": [
        "Protección antivirus avanzada",
        "Detección y eliminación de malware",
        "Compatibilidad con sistemas operativos Windows, macOS y Linux",
        "Actualizaciones automáticas para mantener la seguridad al día"
      ],
      "note": "La licencia se activa digitalmente y es válida para uso personal en un dispositivo",
      "sort_order": 370,
      "cat_sort_order": 140,
      "palette": "eset_nod",
      "stock_quantity": null,
      "active": true,
      "out_of_stock": false,
      "is_oferta": true
    },
    {
      "id": "23",
      "filter": "software",
      "name": "Office 2021 PERMANENTE",
      "brand": "Microsoft",
      "sub": "Permanente - 1 PC o Mac",
      "description": "",
      "type": "Licencia permanente",
      "duration": "Permanente",
      "pen": 48,
      "original_pen": 65,
      "banner_url": "banners/office_2021_banner.png",
      "features": [
        "Acceso a las últimas herramientas de productividad de Office",
        "Incluye aplicaciones como Word, Excel, PowerPoint y Outlook",
        "Uso personal y profesional sin restricciones",
        "Instalación digital sencilla y rápida"
      ],
      "note": "La licencia es válida para un solo dispositivo y no requiere renovación",
      "sort_order": 380,
      "cat_sort_order": 50,
      "palette": "office2021",
      "stock_quantity": null,
      "active": true,
      "out_of_stock": false,
      "is_oferta": false
    },
    {
      "id": "27",
      "filter": "software",
      "name": "ESET Internet Security",
      "brand": "ESET",
      "sub": "1 año - 1 dispositivo",
      "description": "",
      "type": "Licencia digital",
      "duration": "1 año",
      "pen": 65,
      "original_pen": null,
      "banner_url": "banners/eset_internet_security_banner.png",
      "features": [
        "Antivirus + Firewall",
        "Proteccion bancaria",
        "Anti-phishing"
      ],
      "note": "Version completa con proteccion bancaria y firewall. 1 dispositivo.",
      "sort_order": 390,
      "cat_sort_order": 60,
      "palette": "eset_is",
      "stock_quantity": null,
      "active": true,
      "out_of_stock": false,
      "is_oferta": false
    },
    {
      "id": "16",
      "filter": "musica",
      "name": "Spotify Premium 3 meses CUENTA CREADA",
      "brand": "Spotify",
      "sub": "3 meses - Individual",
      "description": "",
      "type": "Cuenta completa",
      "duration": "3 meses",
      "pen": 30,
      "original_pen": null,
      "banner_url": "assets/a2a8a7b525def6eb.png",
      "features": [
        "Reproducción de música sin anuncios",
        "Descarga de música para reproducción offline",
        "Alta calidad de audio",
        "Acceso a playlists y podcasts",
        "Uso en varios dispositivos"
      ],
      "note": "La cuenta se activa después de la compra y es válida por 3 meses",
      "sort_order": 400,
      "cat_sort_order": 0,
      "palette": "spotify_3m",
      "stock_quantity": null,
      "active": true,
      "out_of_stock": false,
      "is_oferta": false
    },
    {
      "id": "29",
      "filter": "software",
      "name": "Nitro PDF Pro",
      "brand": "Nitro PDF",
      "sub": "Permanente - 1 PC",
      "description": "",
      "type": "Licencia permanente",
      "duration": "Permanente",
      "pen": 35,
      "original_pen": null,
      "banner_url": "banners/nitro_pdf_pro_banner.png",
      "features": [
        "Editar y crear PDFs",
        "OCR incluido",
        "Firma digital"
      ],
      "note": "Alternativa profesional a Acrobat. Licencia permanente para 1 PC.",
      "sort_order": 410,
      "cat_sort_order": 70,
      "palette": "nitropdf",
      "stock_quantity": null,
      "active": true,
      "out_of_stock": false,
      "is_oferta": false
    },
    {
      "id": "31",
      "filter": "software",
      "name": "Perplexity Pro 1 mes",
      "brand": "Perplexity",
      "sub": "1 mes - Cuenta",
      "description": "",
      "type": "Cuenta Pro",
      "duration": "1 mes",
      "pen": 10,
      "original_pen": null,
      "banner_url": "banners/perplexity_pro_1_mes_banner.png",
      "features": [
        "Busqueda con IA avanzada",
        "GPT-4 y Claude incluidos",
        "Sin limites"
      ],
      "note": "Acceso completo a Perplexity Pro con los mejores modelos de IA incluidos.",
      "sort_order": 430,
      "cat_sort_order": 90,
      "palette": "perplexity_mes",
      "stock_quantity": null,
      "active": true,
      "out_of_stock": true,
      "is_oferta": false
    },
    {
      "id": "32",
      "filter": "software",
      "name": "Perplexity Pro 1 año",
      "brand": "Perplexity",
      "sub": "1 año - Cuenta",
      "description": "",
      "type": "Cuenta Pro",
      "duration": "1 año",
      "pen": 55,
      "original_pen": null,
      "banner_url": "banners/perplexity_año_banner.png",
      "features": [
        "Busqueda con IA avanzada",
        "GPT-4 y Claude incluidos",
        "Precio anual"
      ],
      "note": "Plan anual de Perplexity Pro. El mejor precio para busqueda con IA ilimitada.",
      "sort_order": 440,
      "cat_sort_order": 100,
      "palette": "perplexity_año",
      "stock_quantity": null,
      "active": true,
      "out_of_stock": true,
      "is_oferta": false
    },
    {
      "id": "20",
      "filter": "musica",
      "name": "Deezer Premium",
      "brand": "Deezer",
      "sub": "6 meses - Individual",
      "description": "",
      "type": "individual",
      "duration": "6 meses",
      "pen": 28,
      "original_pen": 4,
      "banner_url": "assets/a19e6ae0d7b6dfdb.png",
      "features": [
        "Sin publicidad",
        "Descarga offline",
        "Flow personalizado"
      ],
      "note": "6 meses de Deezer Premium. Flow inteligente que aprende tus gustos musicales.",
      "sort_order": 450,
      "cat_sort_order": 0,
      "palette": "deezer",
      "stock_quantity": null,
      "active": true,
      "out_of_stock": false,
      "is_oferta": false
    },
    {
      "id": "34",
      "filter": "software",
      "name": "Claude Max x20",
      "brand": "Claude AI",
      "sub": "1 mes - Cuenta compartida",
      "description": "",
      "type": "Cuenta compartida",
      "duration": "1 mes",
      "pen": 120,
      "original_pen": null,
      "banner_url": "assets/0e4d74d28d84c7e2.png",
      "features": [
        "Acceso a la herramienta de inteligencia artificial Claude Max x20",
        "Capacidad de procesamiento de lenguaje natural avanzado",
        "Análisis de texto y generación de contenido personalizado",
        "Asistencia en tareas de escritura y edición"
      ],
      "note": "El acceso incluye todas las funcionalidades de la herramienta, incluyendo el procesamiento de lenguaje natural y la generación de contenido personalizado. La cuenta es compartida y es válido solo para un dispositivo, ya se móvil o PC",
      "sort_order": 460,
      "cat_sort_order": 110,
      "palette": "claudeai",
      "stock_quantity": null,
      "active": true,
      "out_of_stock": true,
      "is_oferta": false
    },
    {
      "id": "28",
      "filter": "software",
      "name": "Adobe Acrobat Pro",
      "brand": "Adobe",
      "sub": "Permanente",
      "description": "",
      "type": "Cuenta",
      "duration": "Permanente",
      "pen": 55,
      "original_pen": 60,
      "banner_url": "banners/adobe_acrobat_pro_banner.png",
      "features": [
        "Edición y creación de documentos PDF avanzados",
        "Conversión de archivos a formato PDF",
        "Firma y protección de documentos con certificados digitales",
        "Herramientas de comentario y revisión de documentos"
      ],
      "note": "LICENCIA PERMANENTE USO PARA PC WINDOWS\nSE ENTREGA LICENCIA Y LINK DE DESCARGA DEL PROGRAMA\nUN SOLO PAGO ES PERMANENTE!!!!\nSOLO 1 DISPOSITIVO\nVERSION 2020",
      "sort_order": 470,
      "cat_sort_order": 120,
      "palette": "adobe",
      "stock_quantity": null,
      "active": true,
      "out_of_stock": false,
      "is_oferta": false
    },
    {
      "id": "35",
      "filter": "software",
      "name": "Adobe Creative Cloud 1 mes",
      "brand": "Adobe",
      "sub": "1 mes - Cuenta",
      "description": "",
      "type": "Cuenta",
      "duration": "1 mes",
      "pen": 45,
      "original_pen": 48,
      "banner_url": "assets/c3ac2b98664d016f.png",
      "features": [
        "Acceso a herramientas de diseño gráfico y edición de imagen como Photoshop y Illustrator",
        "Uso de software de edición de video como Premiere Pro y After Effects",
        "Acceso a herramientas de desarrollo web como Dreamweaver y Flash"
      ],
      "note": "El uso de Adobe Creative Cloud requiere una conexión a Internet y un dispositivo compatible para acceder a las herramientas y servicios incluidos en la suscripción.",
      "sort_order": 500,
      "cat_sort_order": 150,
      "palette": "adobe_cc_mes",
      "stock_quantity": null,
      "active": true,
      "out_of_stock": false,
      "is_oferta": false
    },
    {
      "id": "24",
      "filter": "software",
      "name": "Windows 11 Pro PERMANENTE",
      "brand": "Microsoft",
      "sub": "Permanente - 1 PC",
      "description": "",
      "type": "Licencia digital",
      "duration": "Permanente",
      "pen": 38,
      "original_pen": 45,
      "banner_url": "assets/39ed058a3068ba34.png",
      "features": [
        "Activación digital permanente",
        "Compatibilidad con dispositivos de 64 bits",
        "Acceso a herramientas de productividad y seguridad",
        "Uso personal y profesional sin restricciones"
      ],
      "note": "La licencia se activa digitalmente y es válida para un dispositivo, sin necesidad de renovación o suscripción adicional.",
      "sort_order": 510,
      "cat_sort_order": 150,
      "palette": "windows11",
      "stock_quantity": null,
      "active": true,
      "out_of_stock": false,
      "is_oferta": true
    },
    {
      "id": "70",
      "filter": "animeydramas",
      "name": "Rakuten Viki",
      "brand": "Rakuten",
      "sub": "1 mes - Perfil",
      "description": "",
      "type": "Perfil individual",
      "duration": "1 mes",
      "pen": 9,
      "original_pen": 11,
      "banner_url": "assets/6e23484cca94fcae.png",
      "features": [
        "Acceso a un amplio catálogo de dramas y series asiáticas",
        "Disfruta de subtítulos y doblaje en varios idiomas",
        "Nuevos estrenos y episodios agregados regularmente",
        "Calidad de video HD para una experiencia de visualización óptima"
      ],
      "note": "El servicio de Rakuten Viki ofrece contenido bajo demanda, sujeto a los términos y condiciones de uso y disponibilidad de contenido según el plan seleccionado.",
      "sort_order": 520,
      "cat_sort_order": 30,
      "palette": "",
      "stock_quantity": null,
      "active": true,
      "out_of_stock": false,
      "is_oferta": false
    },
    {
      "id": "73",
      "filter": "streaming",
      "name": "FLUJO TV +",
      "brand": "Flujo",
      "sub": "1 mes Perfil",
      "description": "",
      "type": "Perfil individual",
      "duration": "1 mes",
      "pen": 15,
      "original_pen": 18,
      "banner_url": "assets/13d6677f192800c3.png",
      "features": [
        "Disfruta de contenido en alta calidad de video, incluyendo Full HD",
        "Accede a canales en vivo y deportes en directo según el plan seleccionado",
        "Disfruta de una experiencia de visualización sin anuncios en algunos contenidos",
        "Puedes ver tus programas favoritos en varios dispositivos compatibles"
      ],
      "note": "El servicio de streaming requiere una conexión a internet estable para funcionar correctamente y puede variar según la disponibilidad de contenido en tu región.",
      "sort_order": 530,
      "cat_sort_order": 100,
      "palette": "",
      "stock_quantity": null,
      "active": true,
      "out_of_stock": false,
      "is_oferta": true
    },
    {
      "id": "74",
      "filter": "software",
      "name": "Gemini pro + Google One 5TB x 1 año",
      "brand": "Google",
      "sub": "Invitación a tu propio correo",
      "description": "",
      "type": "Cuenta personal",
      "duration": "1 año",
      "pen": 40,
      "original_pen": 45,
      "banner_url": "assets/00a7b5cca9927f74.png",
      "features": [
        "Acceso a Gemini pro, una herramienta de inteligencia artificial avanzada",
        "Inclusión de 5TB de almacenamiento en Google One para archivos y datos",
        "Posibilidad de utilizar Gemini pro para tareas de productividad y automatización",
        "Acceso a funciones de edición y creación de contenido con Gemini pro"
      ],
      "note": "Para la activación se le enviará una invitación por correo al grupo familiar para que obtenga los beneficios. El paquete incluye acceso a todas las funciones de Gemini pro y 5TB de almacenamiento en Google One, permitiendo a los usuarios gestionar y almacenar sus archivos y datos de manera segura y eficiente.",
      "sort_order": 540,
      "cat_sort_order": 120,
      "palette": "",
      "stock_quantity": null,
      "active": true,
      "out_of_stock": false,
      "is_oferta": true
    },
    {
      "id": "75",
      "filter": "software",
      "name": "Gemini Pro + Google One 5TB x 18 meses",
      "brand": "Google",
      "sub": "Invitación a tu propio correo",
      "description": "",
      "type": "Cuenta personal",
      "duration": "18 meses",
      "pen": 55,
      "original_pen": 60,
      "banner_url": "assets/a4304423409f7dca.png",
      "features": [
        "Acceso a Gemini Pro, una herramienta de inteligencia artificial avanzada para mejorar la productividad y la creatividad",
        "Incluye 5TB de almacenamiento en Google One para guardar y acceder a archivos y datos desde cualquier lugar",
        "Permite la integración con otras herramientas y servicios de Google para una experiencia más fluida y eficiente",
        "Ofrece funcionalidades de edición y colaboración en tiempo real para trabajar con otros usuarios de manera efectiva"
      ],
      "note": "Para la activación se le enviará una invitación por correo al grupo familiar para que obtenga los beneficios. El paquete incluye acceso a todas las funciones de Gemini pro y 5TB de almacenamiento en Google One, permitiendo a los usuarios gestionar y almacenar sus archivos y datos de manera segura y eficiente.",
      "sort_order": 550,
      "cat_sort_order": 80,
      "palette": "",
      "stock_quantity": null,
      "active": true,
      "out_of_stock": false,
      "is_oferta": true
    },
    {
      "id": "76",
      "filter": "software",
      "name": "Chat GPT PLUS - CUENTA COMPLETA",
      "brand": "ChatGPT",
      "sub": "Cuenta completa - No renovable",
      "description": "",
      "type": "Cuenta completa",
      "duration": "1 mes",
      "pen": 48,
      "original_pen": 79.9,
      "banner_url": "assets/ef1867ea49fe9199.png",
      "features": [
        "Acceso a la versión premium de Chat GPT con capacidades avanzadas de generación de texto",
        "Análisis de texto y respuesta más precisa y detallada",
        "Capacidad de procesar y responder a preguntas y solicitudes de manera más eficiente",
        "Acceso a una mayor cantidad de conocimientos y datos para respuestas más informadas"
      ],
      "note": "Se le brindará las credenciales para el acceso aproximadamente en 30 min o menos. La cuenta es válida únicamente por 30 días y no es renovable.",
      "sort_order": 560,
      "cat_sort_order": 130,
      "palette": "",
      "stock_quantity": null,
      "active": true,
      "out_of_stock": true,
      "is_oferta": true
    },
    {
      "id": "77",
      "filter": "streaming",
      "name": "DirecTV CUENTA COMPLETA",
      "brand": "DirecTV",
      "sub": "Cuenta completa x 30 días",
      "description": "",
      "type": "Cuenta completa",
      "duration": "30 dias",
      "pen": 59,
      "original_pen": 65,
      "banner_url": "assets/aa923f77e5acfa81.png",
      "features": [
        "Disfruta de deportes en vivo y eventos exclusivos",
        "Puedes crear perfiles personalizados para cada miembro de tu hogar",
        "Contenido disponible en diferentes resoluciones según la calidad de tu conexión a internet",
        "Puedes acceder a contenido de entretenimiento y noticias desde diferentes dispositivos"
      ],
      "note": "CUENTA COMPLETA 5 PERFILES PERO SOLO 2 EN SIMULTÁNEO CON L1MAX Y 2 PERFILES MAS SIN L1MAX, 4 EN SIMULTANEO TOTAL, PARA TODO DISPOSITIVO: Todo el entretenimiento y el fútbol peruano en un solo lugar Disfruta de más de 90 canales en vivo, incluyendo deportes, series, películas, noticias y más, directamente desde tu TV con Liga 1 Max, accede a la transmisión exclusiva de los partidos del fútbol profesional peruano, en vivo y en HD. 🔹 Más de 90 canales nacionales e internacionales. 🔹 Canales deportivos como ESPN, FOX Sports, DSports. 🔹 Transmisión en vivo de la Liga 1 peruana con Liga 1 Max. 🔹 Disponible Activación solo a TV por código. Ideal para ver televisión en cualquier momento y lugar, y seguir todos los partidos de tu equipo favorito.",
      "sort_order": 570,
      "cat_sort_order": 90,
      "palette": "",
      "stock_quantity": null,
      "active": true,
      "out_of_stock": true,
      "is_oferta": true
    }
  ],
  "categories": [
    {
      "id": "1",
      "slug": "streaming",
      "name": "Streaming",
      "image_url": "logo/streaming.png",
      "sort_order": 10
    },
    {
      "id": "2",
      "slug": "musica",
      "name": "Música",
      "image_url": "logo/musica.png",
      "sort_order": 20
    },
    {
      "id": "3",
      "slug": "software",
      "name": "Licencias y Software",
      "image_url": "logo/licenciasysoftware.png",
      "sort_order": 30
    },
    {
      "id": "4",
      "slug": "diseño",
      "name": "Diseño y Educación",
      "image_url": "logo/diseñoyeducacion.png",
      "sort_order": 40
    },
    {
      "id": "5",
      "slug": "animeydramas",
      "name": "Anime y Dramas",
      "image_url": "assets/40bef2b76713e45c.png",
      "sort_order": 50
    }
  ],
  "settings": {
    "name": "Arcangel US",
    "logo": "logo/arcangel-us.png",
    "header_logo": "logo/arcangel-us.png",
    "footer_logo": "logo/arcangel-us.png",
    "tagline": "Plataformas premium · entrega inmediata · garantía total.",
    "description": "Compra cuentas premium de Netflix, Spotify, Disney+, HBO, Office 365 y más. Entrega inmediata, precios bajos y garantía total.",
    "whatsapp": "51929688960",
    "whatsapp_message": "Hola! Quiero comprar una cuenta premium hoy. ¿Cuál es el método de pago?",
    "trust": [
      "Elige el plan que necesitas",
      "Coordina todo por WhatsApp",
      "Resuelve tus dudas antes de comprar"
    ],
    "proof_before": "Más de",
    "proof_count": "230",
    "proof_after": "clientes",
    "proof_bottom": "confían en nosotros",
    "footer": "© 2026 Arcangel US · Cuentas y licencias premium · Atención por WhatsApp",
    "footer_contact_text": "¿Quieres una web así?",
    "footer_contact_label": "Contáctame aquí",
    "footer_contact_phone": "51929688960",
    "footer_contact_message": "¡Hola! Me gustaría crear una plataforma web para mi negocio. ¿Podemos conversar?",
    "show_footer_contact": true,
    "all_label": "Todos",
    "all_image": "logo/todos.png",
    "offers_label": "Promos y Ofertas",
    "offers_image": "logo/ofertas.png",
    "search_placeholder": "Buscar",
    "buy_label": "Comprar ahora por WhatsApp",
    "wave_primary": "#ef2c2c",
    "wave_secondary": "#f87171",
    "wave_teal": "#2dd4bf"
  },
  "revision": 6
};
