(()=>{
 const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),money=n=>'S/ '+(n/100).toFixed(2);
 let session,quote,busy=false;const productId=new URLSearchParams(location.search).get('comprar');
 async function api(path,data){const r=await fetch('/api/shop/'+path,{method:data?'POST':'GET',cache:'no-store',headers:data?{'Content-Type':'application/json','X-Shop-Client':'1','X-Shop-Csrf':session.csrf}:{},...(data?{body:JSON.stringify(data)}:{})});const b=await r.json();if(!r.ok)throw Error(b.error||'No se pudo completar la consulta.');return b;}
 const states={pending:'Enviando al proveedor',processing:'En proceso',delivered:'Entregado',refunded:'Saldo devuelto',review:'En revisión · no repitas la compra'};
 async function refresh(){const data=await api('digital/orders');const root=$('#orders');root.innerHTML=data.items.map(o=>`<article><h3>${esc(o.product_name)}</h3><p>${esc(states[o.status]||o.status)} · ${money(o.amount_cents)}</p><small>${esc(o.order_id)} · ${esc(new Date(o.created_at).toLocaleString('es-PE'))}</small>${o.codes.length?`<h4>Códigos entregados</h4><pre>${esc(o.codes.join('\n'))}</pre>`:''}</article>`).join('')||'<div class="empty-digital"><img src="/logo/fazer-topups.svg" alt=""><h3>Aún no tienes compras digitales</h3><p>Tus compras de juegos y tarjetas aparecerán aquí cuando realices tu primera compra.</p></div>';session=await api('session');$('#balance').textContent='Mi saldo · '+money(session.user.balance_cents);}
 async function start(){try{session=await api('session');await refresh();if(!productId)return;quote=await api('digital/quote?product_id='+encodeURIComponent(productId));const root=$('#checkout');root.hidden=false;root.innerHTML=`<div class="checkout-art"><img src="/logo/fazer-topups.svg" alt="" id="digitalArt"></div><div class="checkout-content"><p class="eyebrow">Juegos y tarjetas</p><h2>${esc(quote.name)}</h2><p>${esc(quote.note)}</p><p>${esc([quote.region,quote.platform].filter(Boolean).join(' · '))}</p><form id="digitalForm">${quote.fields.map((f,i)=>`<label class="field">${esc(f.label)}${f.type==='select'?`<select data-field="${i}" ${f.required?'required':''}><option value="">Selecciona</option>${f.options.map(o=>`<option value="${esc(o.value)}">${esc(o.label)}</option>`).join('')}</select>`:`<input data-field="${i}" maxlength="1000" ${f.required?'required':''} autocomplete="off" placeholder="Ingresa ${esc(f.label)}">`}</label>`).join('')}<button type="button" id="verifyPlayer" class="verify-player" ${quote.fields.length?'':'hidden'}>Verificar ID</button><p id="playerStatus" role="status" aria-live="polite"></p><p class="purchase-help">Una unidad por compra. Revisa los datos antes de confirmar.</p><button class="button primary" type="submit">Confirmar compra · ${money(quote.amount_cents)}</button><p id="purchaseStatus" role="status"></p></form></div>`;
 const art=$('#digitalArt');if(quote.image_url){art.referrerPolicy='no-referrer';art.alt=quote.name;art.onerror=()=>{art.onerror=null;art.src='/logo/fazer-topups.svg';};art.src=quote.image_url;}
 const verify=$('#verifyPlayer'),playerStatus=$('#playerStatus');let validationVersion=0;
 root.querySelectorAll('[data-field]').forEach(el=>el.addEventListener('input',()=>{validationVersion++;playerStatus.textContent='';}));
 verify.onclick=async()=>{const version=validationVersion;verify.disabled=true;playerStatus.textContent='Verificando ID…';try{const fields=Object.fromEntries(quote.fields.map((f,i)=>[f.key,root.querySelector('[data-field="'+i+'"]').value]));const result=await api('digital/validate-id',{product_id:productId,fields});if(version!==validationVersion)return;playerStatus.textContent=result.valid?'ID verificado'+(result.player_name?' · '+result.player_name:'')+(result.region?' · '+result.region:''):'ID no válido. Revisa los datos del jugador.';}catch(e){if(version===validationVersion)playerStatus.textContent=e.message;}finally{verify.disabled=false;}};
 $('#digitalForm').onsubmit=async event=>{event.preventDefault();if(busy)return;busy=true;const button=event.currentTarget.querySelector('button[type=submit]');button.disabled=true;const fields=Object.fromEntries(quote.fields.map((f,i)=>[f.key,root.querySelector(`[data-field="${i}"]`).value]));const key='digital-purchase:'+session.user.id+':'+productId;let request;try{request=JSON.parse(sessionStorage.getItem(key));}catch{}
 if(!request)request={request_id:crypto.randomUUID(),product_id:productId,expected_cents:quote.amount_cents,fields};
 try{sessionStorage.setItem(key,JSON.stringify(request));const result=await api('digital/purchase',request);sessionStorage.removeItem(key);$('#purchaseStatus').textContent=states[result.order.status]||result.order.status;root.querySelector('form').hidden=true;const message=document.createElement('p');message.textContent='Compra registrada. Consulta el estado abajo.';root.append(message);await refresh();}catch(e){$('#purchaseStatus').textContent=e.message;}finally{busy=false;button.disabled=false;}};
 }catch(e){$('#notice').textContent=e.message;const a=document.createElement('a');a.href='/cuenta';a.textContent=' Iniciar sesión / Mi cuenta';$('#notice').append(a);}}
 start();setInterval(()=>{if(session&&!busy)refresh().catch(()=>{});},15000);
})();
