window.renderAdvertising=async({api,esc,toast,current})=>{
 const root=document.querySelector('#mainContent');
 root.innerHTML='<section class="settings-card"><h2>Subir publicidad</h2><form id="advertForm"><label class="field">Título<input name="title" required maxlength="160" placeholder="Ejemplo: Promoción de septiembre"></label><label class="field">Imagen<input name="image" type="file" accept="image/jpeg,image/png,image/webp,image/gif" required></label><p>JPG, PNG, WebP o GIF · hasta 10 MB. Se conserva el archivo original, sea vertical, cuadrado u horizontal.</p><img id="advertPreview" alt="Vista previa" hidden style="max-width:100%;max-height:250px;object-fit:contain"><button class="button primary">Subir y publicar</button><p id="advertStatus" role="status"></p></form></section><section class="settings-card"><h2>Publicidad publicada</h2><div id="advertList" class="advert-grid"></div></section>';
 async function list(){const data=await api('/api/admin/advertising');if(!current())return;root.querySelector('#advertList').innerHTML=data.items.map(t=>'<article class="advert-card"><img loading="lazy" src="/api/admin/advertising/'+esc(t.id)+'" alt="'+esc(t.title)+'"><h3>'+esc(t.title)+'</h3><a class="button secondary" href="/api/admin/advertising/'+esc(t.id)+'?download=1">Descargar original</a><button class="button secondary" data-remove="'+esc(t.id)+'">Retirar</button></article>').join('')||'<p>Todavía no has publicado imágenes.</p>';}
 const form=root.querySelector('#advertForm');let preview;
 form.elements.image.onchange=()=>{if(preview)URL.revokeObjectURL(preview);const file=form.elements.image.files[0],img=root.querySelector('#advertPreview');img.hidden=!file;if(file){preview=URL.createObjectURL(file);img.src=preview;}};
 form.onsubmit=async e=>{e.preventDefault();const button=form.querySelector('button'),status=root.querySelector('#advertStatus'),file=form.elements.image.files[0];if(button.disabled)return;if(!file||file.size>10*1024*1024){status.textContent='Elige una imagen de hasta 10 MB.';return;}button.disabled=true;status.textContent='Subiendo imagen…';try{await api('/api/admin/advertising?title='+encodeURIComponent(form.elements.title.value),{method:'POST',headers:{'Content-Type':file.type},body:file});if(!current())return;form.reset();root.querySelector('#advertPreview').hidden=true;if(preview)URL.revokeObjectURL(preview);status.textContent='Imagen publicada para tus clientes.';await list();}catch(error){status.textContent=error.message;}finally{button.disabled=false;}};
 root.querySelector('#advertList').onclick=async e=>{const button=e.target.closest('[data-remove]');if(!button||!confirm('¿Retirar esta imagen de Publicidad?'))return;button.disabled=true;try{await api('/api/admin/advertising/'+button.dataset.remove+'?action=remove',{method:'POST'});await list();}catch(error){toast(error.message,true);button.disabled=false;}};
 try{await list();}catch(error){toast(error.message,true);}
};