window.renderCommercePanel=async function(ctx){
  const {api,esc,toast}=ctx,customersOnly=!!ctx.customersOnly,paymentsOnly=!!ctx.paymentsOnly,root=document.getElementById('mainContent');
  document.getElementById('pageAction').innerHTML='<button class="button secondary" id="refreshSales">Actualizar ventas</button>';
  document.getElementById('refreshSales').textContent=customersOnly?'Actualizar clientes':paymentsOnly?'Actualizar pagos':'Actualizar ventas';
  root.innerHTML='<div class="loading">Cargando…</div>';
  let data;try{data=await api('/api/admin/commerce');}catch(error){if(ctx.current())root.textContent=error.message;return;}
  if(!ctx.current())return;
  if(!data.enabled){root.innerHTML='<section class="settings-card"><h2>Activar cuentas y compras</h2><p class="section-note">Este apartado necesita MySQL y los secretos COMMERCE_ENABLED=true y COMMERCE_KEY. Sigue la guía CLIENTES-Y-VENTAS.md incluida en la actualización.</p></section>';return;}
  const money=n=>'S/ '+(Number(n)/100).toFixed(2),date=n=>new Date(n).toLocaleString('es-PE');
  const status={yape_pending:'Esperando Yape',review:'Revisión Yape',expired:'Plazo terminado',mp_pending:'Esperando pago',attention:'Requiere atención',pending:'Pendiente',approved:'Aprobada',rejected:'Rechazada',pending_manual:'Venta anterior sin entregar',delivered:'Entregado',refunded:'Saldo devuelto',available:'Disponible',sold:'Vendida aquí',external:'Vendida por WhatsApp',retired:'Retirada',cancelled:'Cancelada por reemplazo'};
  const deliveryText=d=>[['Usuario / licencia',d.username],['Contraseña',d.password],['URL de acceso',d.url],['Perfil',d.profile],['PIN',d.pin],['Inicio',d.starts_on],['Término',d.expires_on],['Instrucciones',d.notes]].filter(([,v])=>v).map(([k,v])=>k+': '+v).join('\n');
  const accountFields=()=>'<div class="field-grid"><label class="field"><span>Usuario, correo o licencia</span><input name="username" maxlength="300" autocomplete="off"></label><label class="field"><span>Contraseña de la cuenta</span><input name="password" type="password" maxlength="500" autocomplete="new-password"></label><label class="field"><span>URL de acceso (opcional)</span><input name="url" type="url" maxlength="1000" placeholder="https://"></label><label class="field"><span>Perfil (opcional)</span><input name="profile" maxlength="100"></label><label class="field"><span>PIN (opcional)</span><input name="pin" maxlength="100" autocomplete="off"></label><label class="field"><span>Fecha de inicio (opcional)</span><input name="starts_on" type="date"></label><label class="field"><span>Fecha de término (opcional)</span><input name="expires_on" type="date"></label></div><label class="field"><span>Instrucciones o datos de entrega</span><textarea name="notes" maxlength="5000"></textarea></label><label class="check-field account-renewal-toggle"><input name="renewable" type="checkbox">Permitir renovación para esta cuenta</label>';
  const products=ctx.state().products,productName=id=>products.find(p=>p.id===id)?.name||id;
  const asset=value=>/^https?:\/\//.test(value||'')?value:'/'+String(value||'logo/arcangel-us.png').replace(/^\//,'');
  const productOptions=products.map(p=>`<option value="${esc(p.id)}">${esc(p.name)}</option>`).join('');
  const cellId=id=>`<span class="inventory-id" title="${esc(id)}">#${esc(id.slice(0,8))}</span>`;
  const cellCode=code=>code?`<strong class="inventory-id account-code">${esc(code)}</strong>`:'—';
  const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Lima',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
  function timeRemaining(order){
    if(order.status!=='delivered')return '<span class="help">Servicio inactivo</span>';
    if(!order.expires_on)return '<span class="help">Sin fecha definida</span><small class="sales-subline">Define el término al editar la cuenta.</small>';
    const days=Math.round((Date.parse(order.expires_on+'T00:00:00Z')-Date.parse(today()+'T00:00:00Z'))/86400000);
    const label=days<0?'Vencida':days===0?'Vence hoy':days===1?'Queda 1 día':`Quedan ${days} días`;
    return cellStatus(days<0?'rejected':days<=3?'pending':'approved',label)+`<small class="sales-subline">Vence ${esc(new Date(order.expires_on+'T12:00:00Z').toLocaleDateString('es-PE',{timeZone:'America/Lima'}))}</small>`;
  }
  const cellDate=value=>`<time datetime="${esc(new Date(value).toISOString())}">${esc(date(value))}</time>`;
  const cellStatus=(value,label=status[value])=>`<span class="badge sales-state ${esc(value)}">${esc(label||value)}</span>`;
  const cellProduct=(id,name)=>{const p=products.find(p=>p.id===id)||products.find(p=>p.name===name);return `<div class="inventory-platform"><img src="${esc(asset(p?.logo_url||p?.banner_url))}" alt="Logo de ${esc(name)}" loading="lazy"><div><strong>${esc(name)}</strong><small>${esc(p?.brand||'')}</small></div></div>`;};
  const rowAttrs=(value,search)=>`data-sales-row data-state="${esc(value)}" data-search="${esc(search.toLocaleLowerCase('es'))}"`;
  function salesTable(key,label,columns,rows,filters=null,searchHint=''){
    return `<div id="${key}" class="sales-table-section">${filters?`<div class="sales-table-tools"><label class="field"><span>Buscar en ${label.toLocaleLowerCase('es')}</span><input type="search" data-sales-search placeholder="${esc(searchHint)}" maxlength="300"></label><label class="field"><span>Estado</span><select data-sales-status>${filters.map(([value,title])=>`<option value="${value}">${title}</option>`).join('')}</select></label></div>`:''}<div class="inventory-results"><h3>${esc(label)} <span class="badge" data-sales-count></span></h3><p class="help">Desliza la tabla para ver todas las columnas.</p></div><div class="inventory-table-wrap sales-table-wrap" role="region" aria-label="Tabla de ${esc(label.toLocaleLowerCase('es'))}" tabindex="0"><table class="inventory-table sales-table"><thead><tr>${columns.map(c=>`<th scope="col">${c}</th>`).join('')}</tr></thead><tbody>${rows}<tr data-sales-empty hidden><td colspan="${columns.length}" class="inventory-empty">No hay registros que coincidan con estos filtros.</td></tr></tbody></table></div><div class="inventory-pagination"><span data-sales-summary role="status"></span><label>Filas por página <select data-sales-size aria-label="Filas por página de ${esc(label.toLocaleLowerCase('es'))}">${[10,25,50,100].map(n=>`<option value="${n}">${n}</option>`).join('')}</select></label><div class="row-actions"><button class="button secondary small" type="button" data-sales-prev>Anterior</button><button class="button secondary small" type="button" data-sales-next>Siguiente</button></div></div></div>`;
  }
  function bindSalesTable(key){
    const box=root.querySelector('#'+key),rows=[...box.querySelectorAll('[data-sales-row]')];
    const saved=window.renderCommercePanel.tableFilters||(window.renderCommercePanel.tableFilters={});
    const state=saved[key]||(saved[key]={search:'',status:'all',size:25,page:1});
    const search=box.querySelector('[data-sales-search]'),filter=box.querySelector('[data-sales-status]'),size=box.querySelector('[data-sales-size]');
    if(search)search.value=state.search;if(filter)filter.value=state.status;size.value=String(state.size);
    const allowed=()=>{if(busy)return false;if(ctx.isDirty()){toast('Guarda o cancela los cambios antes de filtrar o cambiar de página.',true);return false;}return true;};
    function draw(){
      const query=state.search.trim().toLocaleLowerCase('es'),matches=rows.filter(row=>(!search||row.dataset.search.includes(query))&&(!filter||state.status==='all'||(state.status==='active'?row.dataset.state!=='resolved':row.dataset.state===state.status)));
      const pages=Math.max(1,Math.ceil(matches.length/state.size));state.page=Math.max(1,Math.min(state.page,pages));const start=(state.page-1)*state.size,visible=new Set(matches.slice(start,start+state.size));
      rows.forEach(row=>row.hidden=!visible.has(row));box.querySelector('[data-sales-empty]').hidden=matches.length>0;box.querySelector('[data-sales-count]').textContent=matches.length;
      box.querySelector('[data-sales-summary]').textContent=`${matches.length?start+1:0}–${Math.min(start+state.size,matches.length)} de ${matches.length} registros · Página ${state.page} de ${pages}`;
      box.querySelector('[data-sales-prev]').disabled=state.page===1;box.querySelector('[data-sales-next]').disabled=state.page===pages;
    }
    if(search)search.oninput=()=>{if(!allowed()){search.value=state.search;return;}state.search=search.value;state.page=1;draw();};
    if(filter)filter.onchange=()=>{if(!allowed()){filter.value=state.status;return;}state.status=filter.value;state.page=1;draw();};
    size.onchange=()=>{if(!allowed()){size.value=String(state.size);return;}state.size=Number(size.value);state.page=1;draw();};
    box.querySelector('[data-sales-prev]').onclick=()=>{if(allowed()){state.page--;draw();}};box.querySelector('[data-sales-next]').onclick=()=>{if(allowed()){state.page++;draw();}};
    box.querySelectorAll('.inventory-platform img').forEach(img=>img.onerror=()=>{img.hidden=true;});draw();
  }
  root.innerHTML=`<div class="stats commerce-stats" style="grid-template-columns:repeat(auto-fit,minmax(180px,1fr))" ${customersOnly?'hidden':''}><div class="stat" ${paymentsOnly?'':'hidden'}><span>Recargas por revisar</span><strong>${data.summary.pending_topups}</strong></div><div class="stat available" ${paymentsOnly?'hidden':''}><span>Cuentas disponibles</span><strong>${data.summary.available}</strong></div><div class="stat" ${paymentsOnly?'hidden':''}><span>Clientes registrados</span><strong id="customerTotal">${data.summary.customers}</strong></div></div><nav class="commerce-tabs" aria-label="Secciones de ventas" ${customersOnly?'hidden':''}><button class="button secondary" data-sales-tab="salesTopups">Recargas</button><button class="button secondary" data-sales-tab="salesYape">Yape automático</button><button class="button secondary" data-sales-tab="salesInventory">Inventario de cuentas</button><button class="button secondary" data-sales-tab="salesOrders">Ventas realizadas</button><button class="button secondary" data-sales-tab="salesReports">Reportes <span id="reportCount"></span></button><button class="button secondary" data-sales-tab="salesReplacements">Reemplazos <span id="replacementCount"></span></button></nav>
    <section id="salesTopups" class="settings-card"><h2>Recargas</h2><p class="section-note">Las solicitudes por QR manual requieren tu revisión. Yape automático se gestiona en su apartado. Mercado Pago acredita los pagos confirmados cuando está configurado. Últimas 200 solicitudes; incidencias y revisiones primero.</p>${salesTable('topupsTable','Recargas',['ID','Cliente','Método','Monto','Fecha','Estado','Observación','Acciones'],data.topups.map(t=>`<tr ${rowAttrs(t.status,[t.email,t.entry_id,t.reference,t.note].join(' '))}><td>${cellId(t.entry_id)}</td><td class="inventory-email"><strong>${esc(t.customer_username||t.email)}</strong><small class="sales-subline">${esc(t.email)}</small></td><td>${t.kind==='yape_topup'?'Yape automático':t.kind==='mp_topup'?'Mercado Pago':t.kind==='admin_topup'?'Agregado por administrador':'Yape / Plin manual'}</td><td class="sales-money">${money(t.amount_cents)}</td><td>${cellDate(t.created_at)}</td><td>${cellStatus(t.status)}</td><td class="sales-note">${esc(t.note||'—')}</td><td>${t.kind==='topup'&&t.status==='pending'?`<details class="sales-actions"><summary>Revisar recarga</summary><form class="topup-review sales-row-form" data-id="${esc(t.entry_id)}"><p class="help">${esc(t.email)} · ${money(t.amount_cents)}</p><label class="check-field"><input type="checkbox" name="verified">Verifiqué el ingreso y el importe</label><label class="field"><span>Nota de revisión (opcional)</span><input name="note" maxlength="400"></label><div class="row-actions"><button type="submit" class="button primary small" name="decision" value="approve">Aprobar</button><button type="submit" class="button secondary small" name="decision" value="reject">Rechazar</button><button type="reset" class="button ghost small">Cancelar</button></div></form></details>`:'<span class="help">'+(t.kind==='yape_topup'?'Ver en Yape automático':t.kind==='mp_topup'?'Confirmación automática':t.kind==='admin_topup'?'Saldo acreditado':'Revisión terminada')+'</span>'}</td></tr>`).join(''),[['all','Todos los estados'],['pending','Pendientes'],['yape_pending','Esperando Yape'],['review','Revisión Yape'],['expired','Plazo terminado'],['mp_pending','Esperando Mercado Pago'],['attention','Requiere atención'],['approved','Aprobadas'],['rejected','Rechazadas']],'Correo, solicitud o nota')}</section>
    <section id="salesYape" class="settings-card"></section>
    <section id="salesInventory" class="settings-card"><h2>Inventario de cuentas</h2><p class="section-note">Carga las cuentas aquí y elige «Entrega automática» al editar el producto. Cada cuenta se entrega una sola vez. Para una venta por WhatsApp, márcala como vendida aquí después de atenderla.</p><div class="inventory-export-box"><div><h3>Descargar cuentas en Excel</h3><p class="help">Incluye correo, contraseña, perfil, PIN, comprador, fechas, importe total y renovaciones. La descarga es solo para tu panel.</p></div><div class="row-actions"><button class="button primary" type="button" id="downloadActiveAccounts">Descargar activas</button><button class="button secondary" type="button" id="downloadExpiredAccounts">Descargar vencidas</button></div></div>
      <details class="inventory-create"><summary>＋ Agregar cuentas al inventario</summary><fieldset id="inventoryCreateFields"><label class="field"><span>Producto al que agregarás las cuentas</span><select id="inventoryEntryProduct" required>${productOptions}</select></label>
      <form id="singleInventoryForm" class="inventory-entry"><h3>Agregar una cuenta</h3>${accountFields()}<button class="button primary" type="submit">Guardar cuenta</button></form>
      <details class="bulk-inventory"><summary>Cargar varias cuentas a la vez</summary><form id="inventoryForm"><label class="field"><span>Lista de cuentas</span><textarea name="items" rows="5" required placeholder="usuario | contraseña | instrucciones" maxlength="800000"></textarea><small>Una cuenta por línea, hasta 200. Formato corto: usuario | contraseña | instrucciones. Formato completo: usuario | contraseña | instrucciones | URL | perfil | PIN. No uses el carácter | dentro de los campos.</small></label><button class="button secondary" type="submit">Guardar lote de cuentas</button></form></details>
      </fieldset></details>
      <div id="inventoryEditor" class="inventory-editor" hidden><p class="eyebrow">EDITAR DATOS DE LA CUENTA</p><h3 id="inventoryEditTitle"></h3><p class="help">Si ya se vendió en la tienda, el comprador verá los datos corregidos. Editar no cambia su estado, el stock ni el cobro. Guarda o cancela para continuar.</p><form id="editInventoryForm">${accountFields()}<div class="row-actions"><button class="button primary" type="submit">Guardar cambios de la cuenta</button><button class="button secondary" type="button" id="cancelInventoryEdit">Cancelar edición</button></div></form></div>
      <h3 class="inventory-manage-heading">Gestionar cuentas</h3>
      <div class="inventory-filters"><label class="field"><span>Plataforma / producto</span><select id="inventoryProduct"><option value="">Todos los productos</option>${productOptions}</select></label><label class="field"><span>Correo, usuario o perfil</span><input id="inventorySearch" type="search" placeholder="Buscar una cuenta…" maxlength="300"></label><label class="field"><span>Estado de la cuenta</span><select id="inventoryStatus"><option value="">Todos los estados</option>${['available','sold','external','retired','cancelled'].map(s=>`<option value="${s}">${status[s]}</option>`).join('')}</select></label></div>
      <p class="help" id="inventorySummary"></p><div id="inventoryList" class="inventory-list"></div>
      </section>
    <section id="salesOrders" class="settings-card"><h2>Ventas realizadas</h2><div id="orderEditor" class="inventory-editor" hidden><h3 id="orderEditTitle">Editar cuenta entregada</h3><p class="help">El cliente verá los datos actualizados. Se conserva la compra, su importe y el estado de la venta.</p><form id="editOrderForm">${accountFields()}<div class="row-actions"><button class="button primary" type="submit">Guardar datos de la cuenta vendida</button><button class="button secondary" type="button" id="cancelOrderEdit">Cancelar edición</button></div></form></div><p class="section-note">Últimas 200 ventas. El importe total incluye la compra y las renovaciones aprobadas de cada cuenta.</p>${salesTable('ordersTable','Ventas realizadas',['Compra','Plataforma / producto','Cuenta','Usuario comprador','Tiempo restante','Importe total','Entrega','Fecha','Estado','Acciones'],data.orders.map(o=>{const total=o.total_amount_cents??o.amount_cents;return `<tr ${rowAttrs(o.status,[o.order_id,o.account_code,o.account_username,o.account_profile,o.product_name,o.email,o.customer_username].join(' '))}><td>${cellId(o.order_id)}</td><td>${cellProduct(o.product_id,o.product_name)}</td><td class="inventory-email">${cellCode(o.account_code)}<small class="sales-subline">${esc(o.account_username||'—')}</small><small class="sales-subline">${esc(o.account_profile)}</small></td><td class="inventory-email"><strong>${esc(o.customer_username||o.email)}</strong><small class="sales-subline">${esc(o.email)}</small></td><td data-order-expiry="${esc(o.order_id)}">${timeRemaining(o)}</td><td class="sales-money">${money(total)}${o.renewal_total_cents?`<small class="sales-subline">Incluye renovaciones: ${money(o.renewal_total_cents)}</small>`:''}</td><td>${o.delivery_mode==='automatic'?'Automática':'Manual'}</td><td>${cellDate(o.created_at)}</td><td>${cellStatus(o.status)}</td><td><div class="sales-row-actions">${o.status==='delivered'?`<button class="button secondary small" type="button" data-edit-order="${esc(o.order_id)}">Editar cuenta vendida</button>`:''}${o.status!=='refunded'?`<details class="sales-actions"><summary>Devolver saldo</summary><form class="refund-form sales-row-form" data-id="${esc(o.order_id)}"><label class="check-field"><input type="checkbox" required>Devolver ${money(total)} a este cliente</label><div class="row-actions"><button type="submit" class="button danger ghost small">Confirmar devolución</button><button type="reset" class="button ghost small">Cancelar</button></div></form></details>`:'<span class="help">Saldo devuelto</span>'}</div></td></tr>`;}).join(''),[['all','Todos los estados'],['pending_manual','Ventas anteriores sin entregar'],['delivered','Entregados'],['refunded','Saldo devuelto']],'Código de cuenta, usuario, correo o producto')}</section>
    <section id="salesReports" class="settings-card"><h2>Reportes de cuentas</h2><p class="section-note">Revisa la falla indicada por el cliente, corrige su cuenta y responde. La respuesta y el estado se muestran en Mis cuentas y compras.</p><div id="reportsList">Consultando reportes…</div></section>
    <section id="salesReplacements" class="settings-card"><h2>Reemplazos de cuentas</h2><p class="section-note">Aquí queda el historial de cada reemplazo. La cuenta anterior se conserva como cancelada y no vuelve a publicarse; la cuenta nueva queda asociada a la compra.</p><div id="replacementsList">Consultando reemplazos…</div></section>
    <section id="salesCustomers" class="settings-card"><h2>Clientes y usuarios</h2><p class="section-note">Crea accesos de cliente y administra su estado. Cada usuario tiene su propia billetera y compras.</p>
      <details class="customer-create"><summary>＋ Crear usuario</summary><form id="createCustomerForm"><div class="field-grid"><label class="field"><span>Usuario</span><input name="username" required minlength="3" maxlength="40" autocomplete="off" autocapitalize="none" placeholder="Ej. lucia123"></label><label class="field"><span>Rol</span><select name="role"><option value="customer">Cliente</option><option value="reseller">Revendedor</option></select></label><label class="field"><span>Correo del cliente</span><input name="email" type="email" maxlength="254" required autocomplete="off"></label><label class="field"><span>Contraseña del cliente</span><input name="password" type="password" minlength="12" maxlength="128" required autocomplete="new-password"></label><label class="field"><span>Repetir contraseña</span><input name="confirm_password" type="password" minlength="12" maxlength="128" required autocomplete="new-password"></label></div><p class="help">Mínimo 12 caracteres. Se crea con saldo S/ 0.00 y los precios del rol elegido. Ninguno de estos roles accede a tu panel. Al terminar recibirás su código de recuperación para entregárselo junto con la contraseña.</p><div class="row-actions"><button type="submit" class="button primary">Crear usuario</button><button type="button" class="button secondary" id="cancelCreateCustomer">Cancelar</button></div></form></details>
      <div id="createdCustomerReceipt" class="customer-receipt" hidden></div><div id="customerRecovery" class="customer-receipt" hidden></div>
      <section id="customerEditor" class="inventory-editor" hidden><h3 id="customerEditTitle"></h3><form id="editCustomerForm"><p class="help" id="customerEditHelp"></p><div class="field-grid" id="customerIdentityFields"><label class="field"><span>Usuario</span><input name="username" required minlength="3" maxlength="40" autocomplete="off" autocapitalize="none"></label><label class="field"><span>Rol y precios</span><select name="role"><option value="customer">Cliente</option><option value="reseller">Revendedor</option></select></label></div><div id="customerBalanceFields" hidden><div class="customer-balance-summary"><span>Saldo actual <strong id="customerBalanceCurrent"></strong></span><span>Saldo después de agregar <strong id="customerBalanceNext" aria-live="polite"></strong></span></div><div class="field-grid"><label class="field"><span>Monto a agregar (S/)</span><input name="amount_soles" type="number" min="0.01" max="1000000" step="0.01" inputmode="decimal" required disabled placeholder="Ej. 20.00"></label><label class="field"><span>Nota para el historial (opcional)</span><input name="note" maxlength="400" disabled placeholder="Ej. Recarga recibida por Yape"></label></div><p class="help">La nota también será visible para el cliente.</p></div><div class="field-grid" id="customerPasswordFields"><label class="field"><span>Nueva contraseña</span><input name="password" type="password" required minlength="12" maxlength="128" autocomplete="new-password"></label><label class="field"><span>Repetir nueva contraseña</span><input name="confirm_password" type="password" required minlength="12" maxlength="128" autocomplete="new-password"></label></div><div class="row-actions"><button class="button primary" type="submit" id="saveCustomerEdit">Guardar cambios</button><button class="button secondary" type="button" id="cancelCustomerEdit">Cancelar</button></div></form></section><div class="customer-counts" id="customerCounts"></div><form id="customerSearch" class="customer-tools"><label class="field"><span>Buscar cliente</span><input name="search" type="search" maxlength="100" placeholder="Usuario o correo electrónico"></label><label class="field"><span>Estado del usuario</span><select name="status"><option value="all">Todos los clientes</option><option value="active">Activos</option><option value="suspended">Suspendidos</option><option value="deleted">Eliminados</option></select></label><button class="button secondary">Buscar</button></form><div id="customerList"></div></section>`;
  let busy=false,batch=crypto.randomUUID(),singleBatch=crypto.randomUUID();
  const sections=customersOnly?['salesCustomers']:paymentsOnly?['salesTopups','salesYape']:['salesInventory','salesOrders','salesReports','salesReplacements'];
  const sectionKey=paymentsOnly?'paymentSection':'section';
  const switchSection=id=>{id=sections.includes(id)?id:sections[0];root.querySelectorAll('.settings-card[id^=sales]').forEach(el=>el.hidden=el.id!==id);root.querySelectorAll('[data-sales-tab]').forEach(el=>{el.hidden=!sections.includes(el.dataset.salesTab);el.classList.toggle('primary',el.dataset.salesTab===id);el.classList.toggle('secondary',el.dataset.salesTab!==id);el.setAttribute('aria-current',el.dataset.salesTab===id?'page':'false');});if(!customersOnly)window.renderCommercePanel[sectionKey]=id;};
  root.querySelector('.commerce-tabs').setAttribute('aria-label',paymentsOnly?'Secciones de pagos':'Secciones de ventas');
  root.querySelectorAll('[data-sales-tab]').forEach(button=>button.onclick=()=>{if(ctx.isDirty()){toast('Guarda los datos que estás editando antes de cambiar de sección.',true);return;}switchSection(button.dataset.salesTab);reload();});switchSection(window.renderCommercePanel[sectionKey]);
  const selectedProduct=window.renderCommercePanel.product||'';if(products.some(p=>p.id===selectedProduct)){root.querySelector('#inventoryProduct').value=selectedProduct;root.querySelector('#inventoryEntryProduct').value=selectedProduct;}
  const entryProduct=window.renderCommercePanel.entryProduct;if(products.some(p=>p.id===entryProduct))root.querySelector('#inventoryEntryProduct').value=entryProduct;
  const refresh=async()=>{await ctx.refreshState();if(ctx.current())await window.renderCommercePanel(ctx);};
  async function reload(){if(busy)return;if(ctx.isDirty()){toast('Guarda los datos que estás editando antes de actualizar.',true);return;}busy=true;ctx.busy(true);try{await refresh();}catch(error){toast(error.message,true);}finally{busy=false;ctx.busy(false);}}
  document.getElementById('refreshSales').onclick=reload;
  async function run(form,action,after=refresh){
    if(busy)return;if(form&&root.querySelector('form[data-dirty=true]')&&[...root.querySelectorAll('form[data-dirty=true]')].some(other=>other!==form)){toast('Guarda o cancela los cambios de los otros formularios antes de continuar.',true);return;}const buttons=[...root.querySelectorAll('button')].map(b=>[b,b.disabled]);busy=true;ctx.busy(true);buttons.forEach(([b])=>b.disabled=true);
    try{await action();ctx.dirty(false);window.arcangelAlerts?.refresh();toast('Cambios guardados.');await after();}
    catch(error){toast(error.message,true);}
    finally{busy=false;ctx.busy(false);if(ctx.current())buttons.forEach(([b,disabled])=>{if(b.isConnected)b.disabled=disabled;});}
  }
  const post=(route,body)=>api('/api/admin/commerce/'+route,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});
  root.querySelectorAll('form').forEach(form=>form.addEventListener('input',()=>{if(form.id!=='customerSearch'){form.dataset.dirty='true';ctx.dirty(true);}}));
  root.querySelectorAll('.sales-row-form').forEach(form=>form.addEventListener('reset',()=>{form.dataset.dirty='false';const details=form.closest('details');if(details)details.open=false;ctx.dirty(!!root.querySelector('form[data-dirty=true]'));}));
  bindSalesTable('topupsTable');bindSalesTable('ordersTable');
  if(paymentsOnly)window.renderYapePanel(ctx,root.querySelector('#salesYape'));
  // Refresh the day counters when returning after midnight without losing edits.
  const refreshExpiry=()=>{if(!ctx.current()){document.removeEventListener('visibilitychange',refreshExpiry);return;}for(const order of data.orders){const cell=root.querySelector(`[data-order-expiry="${order.order_id}"]`);if(cell)cell.innerHTML=timeRemaining(order);}};
  if(window.renderCommercePanel.expiryListener)document.removeEventListener('visibilitychange',window.renderCommercePanel.expiryListener);
  window.renderCommercePanel.expiryListener=refreshExpiry;document.addEventListener('visibilitychange',refreshExpiry);
  root.querySelectorAll('.topup-review').forEach(form=>form.onsubmit=e=>{e.preventDefault();const f=new FormData(form),approved=e.submitter?.value==='approve';if(approved&&!f.has('verified')){toast('Marca que verificaste el ingreso antes de aprobar.',true);return;}run(form,()=>post('topup',{entry_id:form.dataset.id,approved,note:f.get('note')}));});
  root.querySelector('#inventoryForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),lines=String(f.get('items')).split('\n').filter(line=>line.trim());if(lines.some(line=>line.split('|').length<2||line.split('|').length>6)){toast('Usa usuario | contraseña | instrucciones, una cuenta por línea.',true);return;}const items=lines.map(line=>{const [username,password,notes='',url='',profile='',pin='']=line.split('|');return {username:username.trim(),password:password.trim(),notes:notes.trim(),url:url.trim(),profile:profile.trim(),pin:pin.trim()};});run(e.target,()=>post('inventory',{product_id:root.querySelector('#inventoryEntryProduct').value,items,request_id:batch}));};
  root.querySelector('#singleInventoryForm').onsubmit=e=>{e.preventDefault();const item=Object.fromEntries(new FormData(e.target));run(e.target,()=>post('inventory',{product_id:root.querySelector('#inventoryEntryProduct').value,items:[item],request_id:singleBatch}));};
  root.querySelectorAll('.refund-form').forEach(form=>form.onsubmit=e=>{e.preventDefault();run(form,()=>post('refund',{order_id:form.dataset.id}));});
  let orderEditing=null;
  const orderEditForm=root.querySelector('#editOrderForm'),orderEditor=root.querySelector('#orderEditor');
  root.querySelector('#cancelOrderEdit').onclick=()=>{if(busy)return;orderEditing=null;orderEditForm.reset();orderEditForm.dataset.dirty='false';orderEditor.hidden=true;ctx.dirty(false);};
  orderEditForm.onsubmit=e=>{e.preventDefault();if(!orderEditing)return;run(orderEditForm,()=>post('order/update',{order_id:orderEditing.id,revision:orderEditing.revision,delivery:Object.fromEntries(new FormData(orderEditForm))}));};
  async function editSoldOrder(id){
    if(busy)return;if(ctx.isDirty()){toast('Guarda o cancela el formulario antes de editar la cuenta.',true);return;}
    busy=true;ctx.busy(true);
    try{const result=await post('order/read',{order_id:id});if(!ctx.current())return;orderEditing={id,revision:result.revision};orderEditForm.reset();for(const [key,value] of Object.entries(result.delivery)){const field=orderEditForm.elements.namedItem(key);if(field)key==='renewable'?field.checked=!!value:field.value=value;}root.querySelector('#orderEditTitle').textContent=result.product_name+' · Compra #'+id.slice(0,8);switchSection('salesOrders');orderEditor.hidden=false;ctx.dirty(true);orderEditor.scrollIntoView({behavior:'smooth',block:'start'});}
    catch(error){toast(error.message,true);}finally{busy=false;ctx.busy(false);}
  }
  root.querySelectorAll('[data-edit-order]').forEach(button=>button.onclick=()=>editSoldOrder(button.dataset.editOrder));
  const reportStatuses={open:'Pendiente',in_progress:'En revisión',resolved:'Resuelto'};
  let reportItems=[];

  function drawReports(){

    root.querySelector('#reportCount').textContent=reportItems.filter(r=>r.status!=='resolved').length||'';
    const list=root.querySelector('#reportsList');
    list.innerHTML=salesTable('reportsTable','Reportes',['ID / compra','Plataforma / producto','Cliente','Cuenta reportada','Problema','Respuesta','Fecha','Estado','Acciones'],reportItems.map(r=>`<tr ${rowAttrs(r.status,[r.report_id,r.order_id,r.product_name,r.email,r.customer_username,r.account_username,r.message,r.owner_reply].join(' '))}><td>${cellId(r.report_id)}<small class="sales-subline">Compra ${cellId(r.order_id)}</small></td><td>${cellProduct('',r.product_name)}</td><td class="inventory-email"><strong>${esc(r.customer_username||r.email)}</strong><small class="sales-subline">${esc(r.email)}</small></td><td class="inventory-email">${esc(r.account_username||'—')}</td><td class="sales-note"><details class="sales-message"><summary>${esc(r.message.slice(0,90))}${r.message.length>90?'…':''}</summary><p>${esc(r.message)}</p></details></td><td class="sales-note">${r.owner_reply?`<details class="sales-message"><summary>${esc(r.owner_reply.slice(0,90))}${r.owner_reply.length>90?'…':''}</summary><p>${esc(r.owner_reply)}</p></details>`:'Sin respuesta'}</td><td>${cellDate(r.created_at)}</td><td>${cellStatus(r.status,reportStatuses[r.status])}</td><td><div class="sales-row-actions">${r.order_status==='delivered'?`<button class="button secondary small" type="button" data-report-order="${esc(r.order_id)}">Editar cuenta de la compra</button>`:''}<details class="sales-actions report-actions"><summary>Responder / gestionar</summary><form class="report-reply sales-row-form" data-id="${esc(r.report_id)}" data-revision="${r.revision}"><label class="field"><span>Estado del reporte</span><select name="status">${Object.entries(reportStatuses).filter(([key])=>r.status!=='resolved'||key==='resolved').map(([key,label])=>`<option value="${key}" ${r.status===key?'selected':''}>${label}</option>`).join('')}</select></label><label class="field"><span>Respuesta para el cliente</span><textarea name="reply" maxlength="3000" rows="4" placeholder="Indica cómo solucionaste la falla.">${esc(r.owner_reply)}</textarea></label><div class="row-actions"><button class="button primary small" type="submit">Guardar respuesta y estado</button><button class="button secondary small" type="reset">Cancelar cambios</button></div></form></details></div></td></tr>`).join(''),[['all','Todos los estados'],['active','Pendientes y en revisión'],['open','Pendientes'],['in_progress','En revisión'],['resolved','Resueltos']],'Cliente, cuenta, compra o problema');
    bindSalesTable('reportsTable');
    list.querySelectorAll('[data-report-order]').forEach(button=>button.onclick=()=>editSoldOrder(button.dataset.reportOrder));
    const forms=[...list.querySelectorAll('.report-reply')];
    function updateDirty(){ctx.dirty(forms.some(f=>f.dataset.dirty==='true'));}
    forms.forEach(form=>{form.oninput=()=>{form.dataset.dirty='true';updateDirty();};form.onreset=()=>{if(busy)return;form.dataset.dirty='false';updateDirty();};form.onsubmit=e=>{e.preventDefault();if(forms.some(f=>f!==form&&f.dataset.dirty==='true')){toast('Guarda o cancela los cambios de los otros reportes antes de continuar.',true);return;}const f=new FormData(form);run(form,()=>post('report/update',{report_id:form.dataset.id,revision:Number(form.dataset.revision),status:f.get('status'),reply:f.get('reply')}));};});
  }

  async function reports(){const result=await api('/api/admin/commerce/reports');if(!ctx.current())return;reportItems=result.reports;drawReports();}
  function drawReplacements(){
    const items=data.replacements||[];root.querySelector('#replacementCount').textContent=items.length||'';
    root.querySelector('#replacementsList').innerHTML=salesTable('replacementsTable','Reemplazos',['ID','Plataforma / producto','Cliente','Cuenta anterior','Cuenta nueva','Compra','Fecha','Estado'],items.map(r=>`<tr ${rowAttrs(r.status,[r.replacement_id,r.order_id,r.product_name,r.email,r.customer_username,r.old_account_code,r.new_account_code,r.old_account,r.new_account].join(' '))}><td>${cellId(r.replacement_id)}</td><td>${cellProduct(r.product_id,r.product_name)}</td><td class="inventory-email"><strong>${esc(r.customer_username||r.email)}</strong><small class="sales-subline">${esc(r.email)}</small></td><td class="inventory-email">${cellCode(r.old_account_code)}<small class="sales-subline">${esc(r.old_account)}</small><small class="sales-subline">Cuenta cancelada</small></td><td class="inventory-email">${cellCode(r.new_account_code)}<small class="sales-subline">${esc(r.new_account)}</small><small class="sales-subline">Cuenta entregada</small></td><td>${cellId(r.order_id)}</td><td>${cellDate(r.created_at)}</td><td>${cellStatus(r.status)}</td></tr>`).join(''),[['all','Todos']],'Cliente, correo o cuenta');bindSalesTable('replacementsTable');
  }
  let editing=null;
  const editForm=root.querySelector('#editInventoryForm'),editor=root.querySelector('#inventoryEditor'),createFields=root.querySelector('#inventoryCreateFields');
  root.querySelector('#cancelInventoryEdit').onclick=()=>{if(busy)return;editing=null;editForm.reset();editForm.dataset.dirty='false';editor.hidden=true;createFields.disabled=false;ctx.dirty(false);};
  editForm.onsubmit=e=>{e.preventDefault();if(!editing)return;run(editForm,()=>post('inventory/update',{inventory_id:editing.id,revision:editing.revision,delivery:Object.fromEntries(new FormData(editForm))}));};
  async function editInventory(id){
    if(busy)return;if(ctx.isDirty()){toast('Guarda o cancela los cambios actuales antes de editar otra cuenta.',true);return;}
    busy=true;ctx.busy(true);
    try{
      const result=await post('inventory/read',{inventory_id:id});if(!ctx.current())return;
      if(!['available','sold','external'].includes(result.state))throw Error('Esta cuenta está retirada.');
      editing={id,revision:result.revision};editForm.reset();
      for(const [key,value] of Object.entries(result.delivery)){const input=editForm.elements.namedItem(key);if(input)key==='renewable'?input.checked=!!value:input.value=value;}
      root.querySelector('#inventoryEditTitle').textContent=productName(inventoryItems.find(i=>i.inventory_id===id)?.product_id)+' · '+result.account_code;
      createFields.disabled=true;root.querySelector('.inventory-create').open=false;editor.hidden=false;ctx.dirty(true);
      editor.scrollIntoView({behavior:'smooth',block:'start'});editForm.elements.namedItem('username').focus({preventScroll:true});
    }catch(error){toast(error.message,true);}finally{busy=false;ctx.busy(false);}
  }
  const filters=window.renderCommercePanel.inventoryFilters||{search:'',status:'',page:1,size:25};
  window.renderCommercePanel.inventoryFilters=filters;
  root.querySelector('#inventorySearch').value=filters.search;root.querySelector('#inventoryStatus').value=filters.status;
  let inventoryItems=[],inventoryRequest=0;
  function drawInventory(){
    if(!ctx.current())return;
    const list=root.querySelector('#inventoryList'),q=filters.search.toLocaleLowerCase('es');
    const items=inventoryItems.filter(i=>(!filters.status||i.state===filters.status)&&(!q||[i.username,i.profile,i.inventory_id,i.account_code,productName(i.product_id)].join(' ').toLocaleLowerCase('es').includes(q)));
    const pages=Math.max(1,Math.ceil(items.length/filters.size));filters.page=Math.max(1,Math.min(filters.page,pages));
    const start=(filters.page-1)*filters.size;
    const cell=value=>esc(value||'—');
    list.innerHTML=`<div class="inventory-results"><h3>Cuentas registradas <span class="badge">${items.length}</span></h3><p class="help">Se consultan las últimas 500 cuentas del producto seleccionado. Los filtros se aplican a esas cuentas.</p></div><div class="inventory-table-wrap" role="region" aria-label="Tabla de cuentas" tabindex="0"><table class="inventory-table"><thead><tr><th scope="col">Código de cuenta</th><th scope="col">Plataforma / producto</th><th scope="col">Correo / usuario</th><th scope="col">Clave</th><th scope="col">URL</th><th scope="col">Perfil</th><th scope="col">PIN</th><th scope="col">Creado</th><th scope="col">Estado</th><th scope="col">Acciones</th></tr></thead><tbody>${items.slice(start,start+filters.size).map(i=>{
      const p=products.find(p=>p.id===i.product_id),label=i.username||i.inventory_id.slice(0,8);
      return `<tr><td>${cellCode(i.account_code)}</td><td><div class="inventory-platform"><img src="${esc(asset(p?.logo_url||p?.banner_url))}" alt="Logo de ${esc(p?.brand||p?.name||'la plataforma')}" loading="lazy"><div><strong>${esc(productName(i.product_id))}</strong><small>${esc(p?.brand||'')}</small></div></div></td><td class="inventory-email">${cell(i.username)}</td><td><div class="inventory-password"><span data-password-value>${i.has_password?'••••••••':'—'}</span>${i.has_password?`<button class="button ghost small" type="button" data-password="${esc(i.inventory_id)}" aria-label="Mostrar clave de ${esc(label)}" aria-pressed="false">Ver</button>`:''}</div></td><td class="inventory-url">${i.url?`<a href="${esc(i.url)}" target="_blank" rel="noopener noreferrer" title="${esc(i.url)}">${esc(i.url)}</a>`:'—'}</td><td>${cell(i.profile)}</td><td><span class="inventory-pin">${cell(i.pin)}</span></td><td><time datetime="${esc(new Date(i.created_at).toISOString())}">${esc(date(i.created_at))}</time></td><td><span class="badge inventory-state ${esc(i.state)}">${status[i.state]||esc(i.state)}</span>${i.renewable?'<small class="sales-subline">Renovable</small>':''}</td><td><details class="inventory-actions"><summary>Gestionar</summary><button class="button secondary small" type="button" data-show="${esc(i.inventory_id)}">Ver datos completos</button><pre class="private-delivery" hidden></pre>${['available','sold','external'].includes(i.state)?`<button class="button primary small" type="button" data-edit="${esc(i.inventory_id)}">Editar cuenta</button>`:''}${i.state==='available'?`<form class="retire-form" data-id="${esc(i.inventory_id)}"><select name="state" aria-label="Acción para ${esc(label)}"><option value="external">Vendida por WhatsApp</option><option value="retired">Retirar del inventario</option></select><label class="check-field"><input type="checkbox" required>Confirmo que ya no estará disponible</label><button class="button ghost small">Aplicar</button></form>`:'<p class="help">Esta cuenta ya no está disponible para nuevas ventas.</p>'}</details></td></tr>`;
    }).join('')||'<tr><td colspan="10" class="inventory-empty">No hay cuentas que coincidan con estos filtros.</td></tr>'}</tbody></table></div><div class="inventory-pagination"><span role="status">${items.length?start+1:0}–${Math.min(start+filters.size,items.length)} de ${items.length} cuentas · Página ${filters.page} de ${pages}</span><label>Cuentas por página <select id="inventoryPageSize">${[25,50,100].map(n=>`<option value="${n}" ${filters.size===n?'selected':''}>${n}</option>`).join('')}</select></label><div class="row-actions"><button class="button secondary small" id="inventoryPrevious" ${filters.page===1?'disabled':''}>Anterior</button><button class="button secondary small" id="inventoryNext" ${filters.page===pages?'disabled':''}>Siguiente</button></div></div>`;
    list.querySelectorAll('.inventory-platform img').forEach(img=>img.onerror=()=>{img.hidden=true;});
    list.querySelector('#inventoryPrevious').onclick=()=>{filters.page--;drawInventory();};list.querySelector('#inventoryNext').onclick=()=>{filters.page++;drawInventory();};
    list.querySelector('#inventoryPageSize').onchange=e=>{filters.size=Number(e.target.value);filters.page=1;drawInventory();};
    list.querySelectorAll('[data-edit]').forEach(button=>button.onclick=()=>editInventory(button.dataset.edit));
    list.querySelectorAll('[data-password]').forEach(button=>button.onclick=async()=>{
      const value=button.previousElementSibling;if(button.getAttribute('aria-pressed')==='true'){value.textContent='••••••••';button.setAttribute('aria-pressed','false');button.setAttribute('aria-label',button.getAttribute('aria-label').replace('Ocultar','Mostrar'));button.textContent='Ver';return;}
      button.disabled=true;try{const result=await post('inventory/read',{inventory_id:button.dataset.password});if(!ctx.current()||!button.isConnected)return;value.textContent=result.delivery.password;button.setAttribute('aria-pressed','true');button.setAttribute('aria-label',button.getAttribute('aria-label').replace('Mostrar','Ocultar'));button.textContent='Ocultar';}catch(error){toast(error.message,true);}finally{button.disabled=false;}
    });
    list.querySelectorAll('[data-show]').forEach(button=>button.onclick=async()=>{const box=button.nextElementSibling;if(!box.hidden){box.textContent='';box.hidden=true;button.textContent='Ver datos completos';return;}button.disabled=true;try{const result=await post('inventory/read',{inventory_id:button.dataset.show});if(!ctx.current()||!button.isConnected)return;box.textContent='Código de cuenta: '+result.account_code+'\n'+deliveryText(result.delivery);box.hidden=false;button.textContent='Ocultar datos';}catch(error){toast(error.message,true);}finally{button.disabled=false;}});
    list.querySelectorAll('.retire-form').forEach(form=>form.onsubmit=e=>{e.preventDefault();if(ctx.isDirty()){toast('Guarda o cancela los cambios antes de retirar una cuenta.',true);return;}run(form,()=>post('inventory/retire',{inventory_id:form.dataset.id,state:new FormData(form).get('state')}));});
  }
  async function inventory(){
    const productId=root.querySelector('#inventoryProduct').value,request=++inventoryRequest;
    const list=root.querySelector('#inventoryList');inventoryItems=[];list.textContent='Consultando cuentas…';
    try{
      const result=await api('/api/admin/commerce/inventory?product_id='+encodeURIComponent(productId));if(!ctx.current()||request!==inventoryRequest)return;
      const totals={};data.inventory.filter(i=>!productId||i.product_id===productId).forEach(i=>totals[i.state]=(totals[i.state]||0)+Number(i.units));
      root.querySelector('#inventorySummary').textContent=Object.entries(totals).map(([s,n])=>`${status[s]}: ${n}`).join(' · ')||'Sin cuentas cargadas.';
      inventoryItems=result.items;drawInventory();
    }catch(error){if(ctx.current()&&request===inventoryRequest)list.textContent=error.message;}
  }
  const excelText=value=>String(value??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
  const excelDate=value=>value?(/^[0-9]{4}-[0-9]{2}-[0-9]{2}$/.test(String(value))?String(value):new Date(value).toLocaleString('es-PE')):'';
  async function accountExportItems(kind){
    try{return (await api('/api/admin/commerce/account-export?status='+encodeURIComponent(kind))).items||[];}catch(error){
      // Keep the button usable while an older published server is rolling out.
      // It already exposes the same protected inventory/read endpoint used by
      // «Ver datos completos», so no credentials are sent to the browser in a
      // normal page load.
      if(!/Ruta no encontrada|404|no encontrada|Método no permitido/i.test(error.message||''))throw error;
      const items=(await api('/api/admin/commerce/inventory')).items||[],ordersById=new Map(data.orders.map(order=>[order.order_id,order])),candidates=items.filter(item=>['sold','external'].includes(item.state));
      const todayValue=today(),matches=[];
      for(const item of candidates){
        const order=ordersById.get(item.order_id),details=await post('inventory/read',{inventory_id:item.inventory_id}),delivery=details.delivery||{},expiresOn=String(delivery.expires_on||order?.expires_on||'').slice(0,10),expired=!!expiresOn&&expiresOn<todayValue;
        if((kind==='expired')!==expired)continue;
        matches.push({account_code:item.account_code,product_name:order?.product_name||productName(item.product_id),product_id:item.product_id,email:delivery.username||order?.account_username||item.username||'',password:delivery.password||'',profile:delivery.profile||order?.account_profile||item.profile||'',pin:delivery.pin||item.pin||'',url:delivery.url||item.url||'',buyer_username:order?.customer_username||'',buyer_email:order?.email||'',order_id:order?.order_id||'',purchased_at:order?.created_at||item.created_at,starts_on:delivery.starts_on||order?.starts_on||'',expires_on:expiresOn,days_remaining:expiresOn?Math.round((Date.parse(`${expiresOn}T00:00:00Z`)-Date.parse(`${todayValue}T00:00:00Z`))/86400000):null,amount_cents:Number(order?.total_amount_cents??order?.amount_cents??0),renewal_total_cents:Number(order?.renewal_total_cents||0),delivery_mode:order?.delivery_mode||'external',status:expired?'Vencida':'Activa',renewable:!!delivery.renewable});
      }
      return matches;
    }
  }
  async function downloadAccountWorkbook(kind,button){
    if(busy)return;
    const title=kind==='expired'?'Cuentas vencidas':'Cuentas activas',fileName=`cuentas-${kind}-${today()}.xls`,original=button.textContent;
    busy=true;button.disabled=true;button.textContent='Preparando Excel…';ctx.busy(true);
    try{
      const items=await accountExportItems(kind),generatedAt=new Date();
      const columns=['Código de cuenta','Plataforma / producto','Correo / usuario','Contraseña','Perfil','PIN','URL de acceso','Usuario que compró','Correo del comprador','ID de compra','Fecha de compra','Inicio','Vencimiento','Días restantes','Importe total (S/)','Renovaciones (S/)','Entrega','Estado','Renovable'];
      const cells=item=>[item.account_code,item.product_name,item.email,item.password,item.profile,item.pin,item.url,item.buyer_username,item.buyer_email,item.order_id,excelDate(item.purchased_at),item.starts_on,item.expires_on,item.days_remaining==null?'Sin fecha':item.days_remaining,(Number(item.amount_cents||0)/100).toFixed(2),(Number(item.renewal_total_cents||0)/100).toFixed(2),item.delivery_mode==='automatic'?'Automática':'Manual',item.status,item.renewable?'Sí':'No'];
      const header=columns.map(column=>`<th>${excelText(column)}</th>`).join('');
      const body=items.map(item=>`<tr>${cells(item).map((value,index)=>`<td class="${index===14||index===15?'money':''}">${excelText(value)}</td>`).join('')}</tr>`).join('')||`<tr><td colspan="${columns.length}" class="empty">No hay cuentas en este estado.</td></tr>`;
      const html=`<!DOCTYPE html><html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel"><head><meta charset="utf-8"><style>body{font-family:Calibri,Arial,sans-serif;color:#1f2937}h1{color:#8e2636;font-size:20px}p{color:#52606d}table{border-collapse:collapse;width:100%;font-size:11px}th{background:#8e2636;color:#fff;border:1px solid #6f1d2b;padding:9px;text-align:left;white-space:nowrap}td{border:1px solid #cfd6df;padding:7px;vertical-align:top}tr:nth-child(even){background:#f7f8fa}.money{mso-number-format:'0.00'}.empty{text-align:center;color:#6b7280;padding:18px}</style></head><body><h1>${excelText(title)}</h1><p>Arcangel US · Generado: ${excelText(generatedAt.toLocaleString('es-PE'))} · Registros: ${items.length}</p><table><thead><tr>${header}</tr></thead><tbody>${body}</tbody></table></body></html>`;
      const blob=new Blob(['\ufeff',html],{type:'application/vnd.ms-excel;charset=utf-8'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=fileName;document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);const noun=items.length===1?'cuenta':'cuentas',stateLabel=items.length===1?(kind==='expired'?'vencida':'activa'):(kind==='expired'?'vencidas':'activas');toast(`${items.length} ${noun} ${stateLabel} descargada${items.length===1?'':'s'} en Excel.`);
    }catch(error){toast(error.message,true);}finally{button.disabled=false;button.textContent=original;busy=false;ctx.busy(false);}
  }
  root.querySelector('#downloadActiveAccounts').onclick=e=>downloadAccountWorkbook('active',e.currentTarget);
  root.querySelector('#downloadExpiredAccounts').onclick=e=>downloadAccountWorkbook('expired',e.currentTarget);
  root.querySelector('#inventoryProduct').onchange=e=>{window.renderCommercePanel.product=e.target.value;filters.page=1;if(e.target.value&&!ctx.isDirty())root.querySelector('#inventoryEntryProduct').value=e.target.value;inventory();};
  root.querySelector('#inventoryEntryProduct').onchange=e=>{batch=crypto.randomUUID();singleBatch=crypto.randomUUID();window.renderCommercePanel.entryProduct=e.target.value;};
  root.querySelector('#inventorySearch').oninput=e=>{filters.search=e.target.value;filters.page=1;drawInventory();};
  root.querySelector('#inventoryStatus').onchange=e=>{filters.status=e.target.value;filters.page=1;drawInventory();};
  const customerFilters=window.renderCommercePanel.customerFilters||{search:'',status:'all'};
  window.renderCommercePanel.customerFilters=customerFilters;
  const customerSearch=root.querySelector('#customerSearch'),createCustomerForm=root.querySelector('#createCustomerForm');
  customerSearch.elements.search.value=customerFilters.search;customerSearch.elements.status.value=customerFilters.status;
  root.querySelector('#cancelCreateCustomer').onclick=()=>{if(busy)return;createCustomerForm.reset();createCustomerForm.dataset.dirty='false';root.querySelector('.customer-create').open=false;ctx.dirty(false);};
  createCustomerForm.onsubmit=e=>{
    e.preventDefault();const values=new FormData(createCustomerForm);
    if(values.get('password')!==values.get('confirm_password')){toast('Las contraseñas no coinciden.',true);return;}
    let result;
    run(createCustomerForm,async()=>{result=await post('customer/create',{username:values.get('username'),email:values.get('email'),password:values.get('password'),role:values.get('role')});},async()=>{
      createCustomerForm.reset();createCustomerForm.dataset.dirty='false';const createBox=root.querySelector('.customer-create');createBox.open=false;createBox.hidden=true;
      const receipt=root.querySelector('#createdCustomerReceipt');
      receipt.innerHTML=`<p class="eyebrow">USUARIO CREADO</p><h3>${esc(result.customer.username)} · ${result.customer.role==='reseller'?'Revendedor':'Cliente'}</h3><p>${esc(result.customer.email)}</p><p class="help">Guarda este código de recuperación para entregárselo al cliente junto con la contraseña que elegiste. También podrás consultarlo desde el botón «Código de recuperación» de este cliente.</p><pre class="private-delivery"></pre><button type="button" class="button secondary" id="downloadCustomerAccess">Descargar código</button><label class="check-field"><input type="checkbox" id="savedCustomerCode">Ya guardé el código de recuperación</label><button type="button" class="button primary" id="closeCustomerReceipt" disabled>Listo</button>`;
      receipt.querySelector('pre').textContent=result.recovery_code;receipt.hidden=false;ctx.dirty(true);
      const close=()=>{if(busy||!root.querySelector('#savedCustomerCode').checked)return;receipt.textContent='';receipt.hidden=true;createBox.hidden=false;result=null;ctx.dirty(false);};
      root.querySelector('#savedCustomerCode').onchange=e=>root.querySelector('#closeCustomerReceipt').disabled=!e.target.checked;
      root.querySelector('#closeCustomerReceipt').onclick=close;
      root.querySelector('#downloadCustomerAccess').onclick=()=>{const link=document.createElement('a'),url=URL.createObjectURL(new Blob([`Arcangel US — Acceso de cliente\nUsuario: ${result.customer.username}\nCorreo: ${result.customer.email}\nCódigo de recuperación: ${result.recovery_code}\nAccede desde /cuenta con la contraseña que te entregó la tienda. Guarda este código en privado.\n`],{type:'text/plain'}));link.href=url;link.download='arcangel-codigo-cliente.txt';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
      customerFilters.status='all';customerFilters.search=result.customer.email;customerSearch.elements.status.value='all';customerSearch.elements.search.value=result.customer.email;
      await customers();receipt.scrollIntoView({behavior:'smooth',block:'start'});
    });
  };
  function clearCustomerRecovery(){const box=root.querySelector('#customerRecovery');box.replaceChildren();box.hidden=true;}
  function showCustomerRecovery(result){
    const box=root.querySelector('#customerRecovery');
    box.innerHTML=`<p class="eyebrow">SOPORTE AL CLIENTE</p><h3>Código de recuperación</h3><p class="customer-recovery-email"></p><p class="help">Confirma que quien solicita ayuda sea el titular de la cuenta antes de entregarle el código.</p>${result.blocked?'<p class="help">Este usuario está suspendido. El código no permite recuperar el acceso mientras siga suspendido.</p>':''}${result.recovery_code?'<label class="field"><span>Código vigente</span><input id="customerRecoveryCode" class="customer-recovery-code" readonly autocomplete="off" spellcheck="false"></label><p class="help">Este código cambia cuando el cliente restablece su contraseña. Vuelve a consultarlo si lo necesita otra vez.</p><button class="button secondary" type="button" id="copyCustomerRecovery">Copiar código</button>':'<p class="help">Esta cuenta se creó con una versión anterior que no guardaba una copia visible del código. Puedes generar uno nuevo: el anterior dejará de servir. Su contraseña, sesión, saldo y compras se conservan.</p><button class="button primary" type="button" id="generateCustomerRecovery">Generar nuevo código y reemplazar el anterior</button>'}<button class="button ghost" type="button" id="closeCustomerRecovery">Cerrar</button>`;
    box.querySelector('.customer-recovery-email').textContent=result.email;box.hidden=false;
    box.querySelector('#closeCustomerRecovery').onclick=()=>{if(!busy)clearCustomerRecovery();};
    if(result.recovery_code){
      const field=box.querySelector('#customerRecoveryCode');field.value=result.recovery_code;
      box.querySelector('#copyCustomerRecovery').onclick=async()=>{if(busy)return;try{await navigator.clipboard.writeText(field.value);toast('Código de recuperación copiado.');}catch{field.focus();field.select();toast('Selecciona Copiar o pulsa Ctrl+C para copiar el código.');}};
    }else box.querySelector('#generateCustomerRecovery').onclick=()=>{if(ctx.isDirty()){toast('Guarda o cancela el formulario antes de generar el código.',true);return;}let next;run(null,async()=>{next=await post('customer/recovery/generate',{user_id:result.user_id});},async()=>showCustomerRecovery(next));};
    box.scrollIntoView({behavior:'smooth',block:'center'});
  }
  let editingCustomer=null;
  const customerEditForm=root.querySelector('#editCustomerForm'),customerEditor=root.querySelector('#customerEditor');
  function closeCustomerEditor(){editingCustomer=null;customerEditForm.reset();customerEditForm.dataset.dirty='false';customerEditor.hidden=true;ctx.dirty(false);}
  root.querySelector('#cancelCustomerEdit').onclick=()=>{if(!busy)closeCustomerEditor();};
  customerEditForm.onsubmit=e=>{
    e.preventDefault();if(!editingCustomer)return;const f=new FormData(customerEditForm),{id,action}=editingCustomer;
    if(action==='password'&&f.get('password')!==f.get('confirm_password')){toast('Las contraseñas no coinciden.',true);return;}
    if(action==='balance'&&!f.get('amount_soles')){toast('Escribe el monto que deseas agregar.',true);return;}
    const values=action==='password'?{password:f.get('password')}:action==='balance'?{amount_soles:f.get('amount_soles'),note:f.get('note'),request_id:crypto.randomUUID()}:{username:f.get('username'),role:f.get('role')};
    run(customerEditForm,()=>post('customer/'+action,{user_id:id,...values}),async()=>{closeCustomerEditor();await customers();});
  };
  function openCustomerEditor(customer,action){
    clearCustomerRecovery();customerEditForm.reset();editingCustomer={id:customer.id,action};
    root.querySelector('#customerEditTitle').textContent=(action==='password'?'Cambiar contraseña · ':action==='balance'?'Agregar saldo · ':'Usuario y rol · ')+(customer.username||customer.email);
    root.querySelector('#customerEditHelp').textContent=action==='password'?'Se cerrarán sus sesiones y se renovará su código de recuperación. Entrega la nueva contraseña al titular de forma privada. Su saldo y compras se conservan.':action==='balance'?'Acredita saldo directamente en la billetera del cliente. Se registrará como saldo agregado por la tienda y podrá verlo en su historial.':'El rol determina el precio que ve y paga. Al guardar tendrá que volver a iniciar sesión. El registro público siempre crea Clientes.';
    for(const [id,visible] of [['customerIdentityFields',action==='role'],['customerBalanceFields',action==='balance'],['customerPasswordFields',action==='password']]){const fields=root.querySelector('#'+id);fields.hidden=!visible;fields.querySelectorAll('input,select').forEach(el=>el.disabled=!visible);}
    customerEditForm.elements.username.value=customer.username||'';customerEditForm.elements.role.value=customer.role;
    root.querySelector('#customerBalanceCurrent').textContent=money(customer.balance_cents);root.querySelector('#customerBalanceNext').textContent=money(customer.balance_cents);
    customerEditForm.elements.amount_soles.oninput=()=>{const cents=Math.round(Number(customerEditForm.elements.amount_soles.value||0)*100);root.querySelector('#customerBalanceNext').textContent=money(customer.balance_cents+(Number.isFinite(cents)?cents:0));};
    customerEditor.hidden=false;ctx.dirty(true);customerEditForm.dataset.dirty='true';customerEditor.scrollIntoView({behavior:'smooth',block:'center'});
  }
  let customerRequest=0;
  async function customers(){
    const request=++customerRequest,{search,status}=customerFilters;
    const result=await api('/api/admin/commerce/customers?search='+encodeURIComponent(search)+'&status='+encodeURIComponent(status));if(!ctx.current()||request!==customerRequest)return;
    root.querySelector('#customerTotal').textContent=result.counts.all;
    root.querySelector('#customerCounts').innerHTML=[['active','Activos'],['suspended','Suspendidos'],['deleted','Eliminados']].map(([key,label])=>`<div><span>${label}</span><strong>${result.counts[key]}</strong></div>`).join('');
    clearCustomerRecovery();
    const list=root.querySelector('#customerList');
    list.innerHTML=salesTable('customersTable','Clientes',['ID','Usuario / correo','Rol','Saldo','Estado','Registro','Acciones'],result.customers.map(c=>`<tr ${rowAttrs(c.deleted_at?'deleted':c.blocked?'suspended':'active',c.username+' '+c.email+' '+c.id)}><td>${cellId(c.id)}</td><td class="inventory-email"><strong>${esc(c.username||'Sin usuario asignado')}</strong><small class="sales-subline">${esc(c.email)}</small></td><td>${cellStatus(c.role,c.role==='reseller'?'Revendedor':'Cliente')}</td><td class="sales-money">${money(c.balance_cents)}</td><td>${cellStatus(c.deleted_at?'deleted':c.blocked?'suspended':'available',c.deleted_at?'Eliminado':c.blocked?'Suspendido':'Activo')}</td><td>${cellDate(c.created_at)}</td><td>${c.deleted_at?`<p class="help">Eliminado el ${esc(date(c.deleted_at))}.</p><button class="button secondary small" type="button" data-customer-restore="${esc(c.id)}">Restaurar suspendido</button>`:`<div class="customer-actions" role="group" aria-label="Acciones de ${esc(c.username||c.email)}"><button class="button small customer-credit" type="button" data-customer-balance="${esc(c.id)}" ${c.blocked?'disabled title="Reactiva al cliente para agregar saldo"':''}><span aria-hidden="true">＋</span> Agregar saldo</button><button class="button secondary small" type="button" data-customer-edit="${esc(c.id)}">Usuario y rol</button><button class="button secondary small" type="button" data-customer-password="${esc(c.id)}">Cambiar contraseña</button><button class="button secondary small" type="button" data-customer-recovery="${esc(c.id)}">Recuperación</button><button class="button secondary small" type="button" data-customer-access="${esc(c.id)}" data-blocked="${c.blocked?'false':'true'}">${c.blocked?'Reactivar':'Suspender'}</button><details class="customer-delete"><summary>Eliminar usuario</summary><form class="delete-customer-form" data-id="${esc(c.id)}"><p class="help">Cerrará su sesión y no podrá entrar. Sus compras y saldo se conservarán. Puedes recuperarlo desde Eliminados.</p><label class="field"><span>Escribe el correo para confirmar</span><input type="email" name="confirm_email" required maxlength="254" autocomplete="off" placeholder="${esc(c.email)}"></label><button class="button danger ghost small" type="submit">Confirmar eliminación</button></form></details></div>`}</td></tr>`).join(''));
    bindSalesTable('customersTable');
    const canManage=()=>{if(busy)return false;if(ctx.isDirty()){toast('Guarda o cancela el formulario y el código de recuperación antes de gestionar usuarios.',true);return false;}return true;};
    list.querySelectorAll('[data-customer-edit],[data-customer-password],[data-customer-balance]').forEach(button=>button.onclick=()=>{if(!canManage())return;const id=button.dataset.customerEdit||button.dataset.customerPassword||button.dataset.customerBalance;openCustomerEditor(result.customers.find(c=>c.id===id),button.dataset.customerBalance?'balance':button.dataset.customerPassword?'password':'role');});
    list.querySelectorAll('[data-customer-recovery]').forEach(button=>button.onclick=async()=>{if(!canManage())return;busy=true;ctx.busy(true);try{const result=await post('customer/recovery',{user_id:button.dataset.customerRecovery});if(ctx.current()&&button.isConnected)showCustomerRecovery(result);}catch(error){toast(error.message,true);}finally{busy=false;ctx.busy(false);}});
    list.querySelectorAll('[data-customer-access]').forEach(button=>button.onclick=()=>{if(!canManage())return;run(null,()=>post('customer',{user_id:button.dataset.customerAccess,blocked:button.dataset.blocked==='true'}),customers);});
    list.querySelectorAll('[data-customer-restore]').forEach(button=>button.onclick=()=>{if(!canManage())return;run(null,()=>post('customer/restore',{user_id:button.dataset.customerRestore}),customers);});
    list.querySelectorAll('.delete-customer-form').forEach(form=>form.onsubmit=e=>{e.preventDefault();if(!canManage())return;run(form,()=>post('customer/delete',{user_id:form.dataset.id,confirm_email:new FormData(form).get('confirm_email')}),customers);});
  }
  customerSearch.onsubmit=e=>{e.preventDefault();if(busy)return;if(ctx.isDirty()){customerSearch.elements.search.value=customerFilters.search;customerSearch.elements.status.value=customerFilters.status;toast('Guarda o cancela el formulario antes de buscar clientes.',true);return;}customerFilters.search=new FormData(e.target).get('search').trim();customerFilters.status=new FormData(e.target).get('status');customers().catch(error=>toast(error.message,true));};
  customerSearch.elements.status.onchange=()=>customerSearch.requestSubmit();
  drawReplacements();
  await Promise.all(customersOnly?[customers()]:paymentsOnly?[]:[inventory(),reports()]).catch(error=>toast(error.message,true));
};
