window.renderCoupons=async function(ctx){
 const root=document.querySelector('#mainContent'),{esc,api,toast}=ctx;
 const post=(path,data)=>api('/api/admin/commerce/coupons/'+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});
 root.innerHTML=`<section class="settings-card"><h2>Crear cupón</h2><p>Un canje por cliente. El límite de usos es total. Vencimiento en horario de Perú.</p><form id="couponForm"><div class="field-grid"><label class="field">Código<input name="code" required pattern="[A-Za-z0-9-]{3,40}" maxlength="40"></label><button class="button secondary" type="button" id="generateCoupon">Generar código</button><label class="field">Tipo<select name="kind"><option value="discount">Descuento en productos (%)</option><option value="balance">Regalar saldo (S/)</option></select></label><label class="field"><span id="couponValueLabel">Porcentaje de descuento</span><input name="value" type="number" required min="1" max="100" step="1"></label><label class="field">Cantidad máxima de canjes<input name="max_uses" type="number" min="1" max="1000000" step="1" required></label><label class="field">Fecha y hora de vencimiento · Perú<input name="expires" type="datetime-local" required></label></div><p class="form-help">El descuento se aplica a todos los productos comprables con saldo. Los productos que solo muestran “Comprar por WhatsApp” quedan excluidos automáticamente.</p><button class="button primary" type="submit">Crear cupón</button><p id="couponError" role="status"></p></form></section><section class="settings-card"><h2>Cupones creados</h2><button class="button secondary" id="refreshCoupons">Actualizar cupones</button><div class="table-wrap" id="couponList"></div></section>`;
 const form=root.querySelector('#couponForm');let busy=false;
 root.querySelector('#generateCoupon').onclick=()=>{form.elements.code.value='ARCA-'+crypto.randomUUID().slice(0,8).toUpperCase();ctx.dirty(true);};
 form.oninput=()=>ctx.dirty(true);
 form.elements.kind.onchange=()=>{const balance=form.elements.kind.value==='balance';root.querySelector('#couponValueLabel').textContent=balance?'Saldo de regalo (S/)':'Porcentaje de descuento';form.elements.value.max=balance?'1000000':'100';form.elements.value.min=balance?'0.01':'1';form.elements.value.step=balance?'0.01':'1';};
 async function list(){try{const data=await api('/api/admin/commerce/coupons');if(!ctx.current())return;root.querySelector('#couponList').innerHTML=`<table class="product-table"><thead><tr><th>Código</th><th>Beneficio</th><th>Usos</th><th>Vence · Perú</th><th>Productos</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>${data.items.map(c=>`<tr><td><strong>${esc(c.code)}</strong></td><td>${c.kind==='discount'?c.value+'%':'S/ '+(c.value/100).toFixed(2)}</td><td>${c.used} / ${c.max_uses}</td><td>${esc(new Date(Number(c.expires_ms)).toLocaleString('es-PE',{timeZone:'America/Lima'}))}</td><td>${c.kind==='balance'?'Billetera':c.products.length?c.products.map(id=>esc(ctx.state().products.find(p=>p.id===id)?.name||id)).join(', '):'Todos'}</td><td>${!c.active?'Desactivado':Date.now()>=Number(c.expires_ms)?'Vencido':c.used>=c.max_uses?'Agotado':'Activo'}</td><td>${c.active?`<button class="button secondary small" data-disable-coupon="${esc(c.code)}">Desactivar</button>`:''}</td></tr>`).join('')||'<tr><td colspan="7">Todavía no hay cupones.</td></tr>'}</tbody></table>`;root.querySelectorAll('[data-disable-coupon]').forEach(b=>b.onclick=async()=>{if(busy)return;busy=true;b.disabled=true;try{await post('disable',{code:b.dataset.disableCoupon});await list();}catch(e){toast(e.message,true);}finally{busy=false;b.disabled=false;}});}catch(e){toast(e.message,true);}}
 form.onsubmit=async e=>{e.preventDefault();if(busy)return;busy=true;const button=form.querySelector('[type=submit]');button.disabled=true;try{const f=new FormData(form);await post('create',{...Object.fromEntries(f),products:[]});form.reset();form.elements.kind.onchange();ctx.dirty(false);toast('Cupón creado.');await list();}catch(e){root.querySelector('#couponError').textContent=e.message;}finally{busy=false;button.disabled=false;}};
 root.querySelector('#refreshCoupons').onclick=list;await list();
};
