window.renderFazer=async({api,esc,current})=>{
 const root=document.querySelector('#mainContent'),base='/api/admin/commerce/fazer/';let cursor=null;
 root.innerHTML=`<section class="settings-card"><h2>Conectar FazerCards</h2><p>Configura el acceso del proveedor y el valor de un dólar en soles.</p><form id="fazerConfig"><label class="field">Clave API<input name="api_key" type="password" autocomplete="new-password" placeholder="La clave se guarda cifrada"></label><label class="field">Tipo de cambio · S/ por US$1<input name="exchange_rate" type="number" min="0.000001" max="1000" step="0.000001" required></label><button class="button primary">Verificar y guardar</button><p role="status" id="fazerStatus"></p></form></section><section class="settings-card"><h2>Catálogo del proveedor</h2><label class="field">Servicio<select id="fazerKind"><option value="topups">Recargas de juegos</option><option value="giftcards">Tarjetas de regalo</option><option value="gamekeys">Claves de juegos</option></select></label><button class="button secondary" id="fazerLoad">Consultar catálogo</button><label class="field" style="margin-top:16px">Buscar en el catálogo<div style="display:flex;align-items:center;gap:10px;border:1px solid #493345;border-radius:10px;padding:0 12px"><svg aria-hidden="true" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="10.5" cy="10.5" r="7.5"/><path d="m16 16 5 5"/></svg><input id="fazerSearch" type="search" placeholder="Buscar juego o tarjeta…" style="width:100%;border:0;background:transparent"></div></label><p id="fazerSearchStatus" role="status"></p><div id="fazerCatalog"></div><button class="button secondary" id="fazerNext" hidden>Ver más</button><div id="fazerOffers"></div></section>`;
 const orderSection=document.createElement('section');orderSection.className='settings-card';orderSection.innerHTML='<h2>Ventas de juegos y tarjetas</h2><button class="button secondary" id="refreshDigitalSales">Actualizar ventas</button><div id="digitalSales"></div>';root.append(orderSection);
 async function sales(){try{const data=await api(base+'orders');if(!current())return;const labels={pending:'Enviando',processing:'En proceso',delivered:'Entregado',refunded:'Saldo devuelto',review:'Revisar con proveedor'};orderSection.querySelector('#digitalSales').innerHTML=data.items.map(o=>`<article><h3>${esc(o.product_name)}</h3><p>${esc(labels[o.status]||o.status)} · S/ ${(o.amount_cents/100).toFixed(2)}</p><p>Cliente: ${esc(o.user_id)} · Pedido: ${esc(o.order_id)} · Proveedor: ${esc(o.provider_id||'Confirmación pendiente')}</p></article>`).join('')||'<p>Aún no hay ventas digitales.</p>';}catch(e){orderSection.querySelector('#digitalSales').textContent=e.message;}}
 orderSection.querySelector('#refreshDigitalSales').onclick=sales;sales();
 const form=root.querySelector('form'),status=root.querySelector('#fazerStatus');
 const search=root.querySelector('#fazerSearch'),searchStatus=root.querySelector('#fazerSearchStatus');
 const normalize=value=>value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
 function filterCatalog(){const q=normalize(search.value.trim()),buttons=[...root.querySelector('#fazerCatalog').children];let count=0;buttons.forEach(button=>{button.hidden=!normalize(button.textContent).includes(q);if(!button.hidden)count++;});searchStatus.textContent=buttons.length?count+' productos encontrados'+(cursor?' · Hay más páginas disponibles.':''):'';}
 let searchTimer;search.oninput=()=>{filterCatalog();clearTimeout(searchTimer);searchTimer=setTimeout(async()=>{if(!search.value.trim())return;await load(false);let previous;while(current()&&search.value.trim()&&cursor&&cursor!==previous){previous=cursor;await load(true);}filterCatalog();},350);};
 try{const c=await api(base+'config');if(!current())return;form.elements.exchange_rate.value=c.exchange_rate||'';form.elements.api_key.placeholder=c.configured?'Clave guardada · dejar vacío para conservarla':'Introduce tu clave API';status.textContent=c.configured?'Clave API guardada y cifrada. El campo permanece vacío por seguridad; solo rellénalo si deseas cambiarla.':'Falta conectar tu cuenta de FazerCards.';}catch(e){status.textContent=e.message;}
 form.onsubmit=async e=>{e.preventDefault();const b=form.querySelector('button');if(b.disabled)return;b.disabled=true;status.textContent='Verificando conexión…';try{const d=await api(base+'config',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(form)))});form.elements.api_key.value='';status.textContent=`Conectado · Plan ${d.status.plan} · Saldo US$ ${d.status.balance}`;}catch(e){status.textContent=e.message;}finally{b.disabled=false;}};
 async function load(next=false){const b=root.querySelector('#fazerLoad'),kind=root.querySelector('#fazerKind').value;if(b.disabled)return;b.disabled=true;try{const data=await api(base+'catalog?'+new URLSearchParams({kind,...(next&&cursor?{cursor}:{})}));if(!current()||kind!==root.querySelector('#fazerKind').value)return;const list=root.querySelector('#fazerCatalog');if(!next)list.innerHTML='';for(const item of data.items||[]){const button=document.createElement('button');button.className='button secondary';button.style.margin='8px';button.textContent=item.name||item.GameName||'Producto';button.onclick=async()=>{try{const offers=await api(base+'offers?'+new URLSearchParams({kind,id:item.category_id||item.game_id}));if(!current())return;root.querySelector('#fazerOffers').innerHTML=`<h3>${esc(offers.name||offers.GameName||item.name)}</h3><p>${esc(offers.note||'')}</p><div class="table-wrap"><table class="product-table"><thead><tr><th>Producto</th><th>Costo USD</th><th>Stock</th><th>Precios en soles y publicación</th></tr></thead><tbody>${(offers.offers||offers.keys||offers.cards||[]).map(o=>`<tr><td>${esc(o.name)}</td><td>${esc(o.price_usd)}</td><td>${esc(o.stock??'Consultar')}</td></tr>`).join('')}</tbody></table></div>`;await window.fazerPublicationControls({root:root.querySelector("#fazerOffers"),api,esc,kind,categoryId:String(item.category_id||item.game_id),categoryName:item.name||item.GameName,offers:offers.offers||offers.keys||offers.cards||[]});}catch(e){status.textContent=e.message;}};list.append(button);}cursor=data.meta?.next_cursor;root.querySelector('#fazerNext').hidden=!data.meta?.has_more||!cursor;filterCatalog();}catch(e){status.textContent=e.message;}finally{b.disabled=false;}}
 root.querySelector('#fazerLoad').onclick=()=>load();root.querySelector('#fazerNext').onclick=()=>load(true);root.querySelector('#fazerKind').onchange=()=>{clearTimeout(searchTimer);search.value='';searchStatus.textContent='';cursor=null;root.querySelector('#fazerNext').hidden=true;root.querySelector('#fazerCatalog').innerHTML='';root.querySelector('#fazerOffers').innerHTML='';};
};



